// AUTO-GENERATED BY specshot (custom template — naming helpers demo)
// Simple barrel using kebabCase for file paths.

export * from "./services/PetsService";

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
