// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  Pet,
  CreatePetRequest,
  petsListPetsResponse,
  petsListPetsParams,
  petsCreatePetPayload,
  petsCreatePetResponse,
  petsGetPetResponse,
} from "./pets.types";

export type {
  Pet,
  CreatePetRequest,
  petsListPetsResponse,
  petsListPetsParams,
  petsCreatePetPayload,
  petsCreatePetResponse,
  petsGetPetResponse,
};

export class petsService extends BaseService<"pets"> {
  constructor(client: ApiClient) {
    super(client, "pets");
  }

  /**
   * listPets
   * List all pets
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `petsListPetsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.pets.listPets(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listPets(
    config?: AppRequestConfig,
  ): Promise<ApiResult<petsListPetsResponse, AppApiErrorData>> {
    return this.client.get<petsListPetsResponse, AppApiErrorData>(
      `/pets`,
      this.withSignal(config),
    );
  }

  /**
   * createPet
   * Create a pet

   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `petsCreatePetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.pets.createPet(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createPet(
    payload: petsCreatePetPayload,
    config?: AppRequestConfig,
  ): Promise<ApiResult<petsCreatePetResponse, AppApiErrorData>> {
    return this.client.post<petsCreatePetResponse, AppApiErrorData>(
      `/pets`,
      payload,
      this.withSignal(config),
    );
  }

  /**
   * getPet
   * Get a pet by ID
   * @param petId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `petsGetPetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.pets.getPet(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getPet(
    petId: string | number,
    config?: AppRequestConfig,
  ): Promise<ApiResult<petsGetPetResponse, AppApiErrorData>> {
    return this.client.get<petsGetPetResponse, AppApiErrorData>(
      `/pets/${petId}`,
      this.withSignal(config),
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  // --- CUSTOM CODE END ---
}
