// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for user --
export const UserSchema = z.object({
  id: z.string(),
  username: z.string(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
});
export type User = z.infer<typeof UserSchema>;

export const CreateUserRequestSchema = z.object({
  username: z.string(),
  email: z.string(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
});
export type CreateUserRequest = z.infer<typeof CreateUserRequestSchema>;

export const LoginResultSchema = z.object({
  token: z.string(),
  expiresIn: z.number().int().optional(),
});
export type LoginResult = z.infer<typeof LoginResultSchema>;

// -- Request & Response Types --

export type userCreateUserPayload = CreateUserRequest;

export type userCreateUserResponse = User;

export type userLoginUserParams = {
  username: string;
  password: string;
};

export type userLoginUserResponse = LoginResult;

export type userGetUserResponse = User;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
