// AUTO-GENERATED BY specshot
import { z } from "zod";

import { Pet, PetSchema } from "./models";

// -- Specific Models for store --
export const StoreSchema = z.object({
  id: z.string(),
  address: z.string(),
  pet: PetSchema.optional(),
});
export type Store = z.infer<typeof StoreSchema>;

export const OrderSchema = z.object({
  id: z.string(),
  petId: z.string(),
  quantity: z.number().optional(),
  shipDate: z.string().optional(),
  status: z.enum(["placed", "approved", "delivered"]),
});
export type Order = z.infer<typeof OrderSchema>;

export const CreateOrderRequestSchema = z.object({
  petId: z.string(),
  quantity: z.number(),
});
export type CreateOrderRequest = z.infer<typeof CreateOrderRequestSchema>;

// -- Request & Response Types --

export type storeListStoresResponse = Store[];

export type storePlaceOrderPayload = CreateOrderRequest;

export type storePlaceOrderResponse = Order;

export type storeGetOrderResponse = Order;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
