// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  User,
  CreateUserRequest,
  LoginResult,
  UserCreateUserPayload,
  UserCreateUserResponse,
  UserLoginUserParams,
  UserLoginUserResponse,
  UserGetUserResponse,
} from "./user.types";

export type {
  User,
  CreateUserRequest,
  LoginResult,
  UserCreateUserPayload,
  UserCreateUserResponse,
  UserLoginUserParams,
  UserLoginUserResponse,
  UserGetUserResponse,
};

export class UserService extends BaseService<"user"> {
  constructor(client: ApiClient) {
    super(client, "user");
  }

  /**
   * createUser
   * Create a user

   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `UserCreateUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.user.createUser(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createUser(
    payload: UserCreateUserPayload,
    config?: AppRequestConfig,
  ): Promise<ApiResult<UserCreateUserResponse, AppApiErrorData>> {
    return this.client.post<UserCreateUserResponse, AppApiErrorData>(
      `/user`,
      payload,
      this.withSignal(config),
    );
  }

  /**
   * loginUser
   * Login a user
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `UserLoginUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.user.loginUser(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public loginUser(
    config?: Omit<AppRequestConfig, "params"> & {
      params?: UserLoginUserParams;
    },
  ): Promise<ApiResult<UserLoginUserResponse, AppApiErrorData>> {
    return this.client.get<UserLoginUserResponse, AppApiErrorData>(
      `/user/login`,
      this.withSignal(config),
    );
  }

  /**
   * getUser
   * Get user by username
   * @param username - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `UserGetUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.user.getUser(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getUser(
    username: string | number,
    config?: AppRequestConfig,
  ): Promise<ApiResult<UserGetUserResponse, AppApiErrorData>> {
    return this.client.get<UserGetUserResponse, AppApiErrorData>(
      `/user/${username}`,
      this.withSignal(config),
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
