// AUTO-GENERATED BY specshot (custom template — Factory Pattern) - DO NOT DELETE MAGIC COMMENTS
// Design Pattern: Factory — create configured service instances per environment/tenant.
// Use case: Multi-tenant apps, different API environments (staging/prod), test isolation.

import type { Pet, CreatePetRequest, PetsListPetsResponse, PetsCreatePetPayload, PetsCreatePetResponse, PetsGetPetResponse } from "./pets.types";
export type { Pet, CreatePetRequest, PetsListPetsResponse, PetsCreatePetPayload, PetsCreatePetResponse, PetsGetPetResponse } from "./pets.types";

import { ApiError } from "./models";

// ─────────────────────────────────────────────
// Service Configuration
// ─────────────────────────────────────────────

export interface PetsServiceConfig {
  baseUrl: string;
  headers?: Record<string, string>;
  timeout?: number;
  retries?: number;
}

// ─────────────────────────────────────────────
// Service Implementation
// ─────────────────────────────────────────────

export class PetsService {
  private _config: Required<PetsServiceConfig>;

  constructor(config: PetsServiceConfig) {
    this._config = {
      timeout: 10000,
      retries: 0,
      headers: {},
      ...config,
    };
  }

  private async _request<T>(
    method: string,
    url: string,
    body?: unknown,
  ): Promise<T> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this._config.timeout);

    let lastError: Error | null = null;
    const maxAttempts = this._config.retries + 1;

    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      try {
        const _res = await fetch(url, {
          method,
          headers: {
            "Content-Type": "application/json",
            ...this._config.headers,
          },
          ...(body ? { body: JSON.stringify(body) } : {}),
          signal: controller.signal,
        });
        clearTimeout(timeoutId);
        if (!_res.ok) {
          const _errBody = await _res.text().catch(() => "");
          throw new ApiError(`${method} ${url} failed: ${_res.status}`, _res.status, _errBody);
        }
        return _res.json() as Promise<T>;
      } catch (err) {
        lastError = err as Error;
        if (attempt < maxAttempts - 1) {
          await new Promise((r) => setTimeout(r, 2 ** attempt * 100));
        }
      }
    }
    clearTimeout(timeoutId);
    throw lastError || new Error("Request failed");
  }

  /**
   * listPets
   * List all pets
   * @throws {ApiError} On non-2xx response
   */
  async listPets(
  ): Promise<PetsListPetsResponse> {
    let _url = `${this._config.baseUrl}/pets`;
    return this._request<PetsListPetsResponse>("get", _url);
  }

  /**
   * createPet
   * Create a pet
   * @throws {ApiError} On non-2xx response
   */
  async createPet(
    body: PetsCreatePetPayload,
  ): Promise<PetsCreatePetResponse> {
    let _url = `${this._config.baseUrl}/pets`;
    return this._request<PetsCreatePetResponse>("post", _url, body);
  }

  /**
   * getPet
   * Get a pet by ID
   * @throws {ApiError} On non-2xx response
   */
  async getPet(
    petId: string | number,
  ): Promise<PetsGetPetResponse> {
    let _url = `${this._config.baseUrl}/pets/${petId}`;
    return this._request<PetsGetPetResponse>("get", _url);
  }

}

// ─────────────────────────────────────────────
// Factory — create pre-configured instances
// ─────────────────────────────────────────────

export class PetsServiceFactory {
  /** Create a production instance. */
  static createProduction(): PetsService {
    return new PetsService({
      baseUrl: "https://api.example.com",
      timeout: 10000,
      retries: 2,
    });
  }

  /** Create a staging instance. */
  static createStaging(): PetsService {
    return new PetsService({
      baseUrl: "https://staging-api.example.com",
      timeout: 15000,
      retries: 1,
    });
  }

  /** Create a test instance with short timeout. */
  static createTest(baseUrl = "http://localhost:8080"): PetsService {
    return new PetsService({
      baseUrl,
      timeout: 2000,
      retries: 0,
    });
  }

  /** Create an authenticated instance. */
  static createWithAuth(baseUrl: string, token: string): PetsService {
    return new PetsService({
      baseUrl,
      headers: { Authorization: `Bearer ${token}` },
      timeout: 10000,
    });
  }
}

// --- CUSTOM CODE START ---
// Add your custom code here. Do not remove these comments.
// --- CUSTOM CODE END ---
