// AUTO-GENERATED BY specshot
import { ApiClient } from "../core/api-client";
export * from "./types";
export * from "./client";
export * from "./plugins";

export * from "./services/pets.service";
import { PetsService } from "./services/pets.service";
export * from "./services/stores.service";
import { StoresService } from "./services/stores.service";

// ==========================================
// API Factory (For SSR and Client)
// ==========================================
export function createApi(client: ApiClient) {
  const instances = new Map<string, any>();
  return {
    client,
    get pets(): PetsService {
      let instance = instances.get("pets");
      if (!instance) {
        instance = new PetsService(client);
        instances.set("pets", instance);
      }
      return instance;
    },
    get stores(): StoresService {
      let instance = instances.get("stores");
      if (!instance) {
        instance = new StoresService(client);
        instances.set("stores", instance);
      }
      return instance;
    },
  } as const;
}

export type ApiInstance = ReturnType<typeof createApi>;

// ==========================================
// Default Client API (Client-side usage only)
// ==========================================
// For SSR, DO NOT use this exported singleton. Instead, create a new client
// per request using `createApiClient()` and `createApi()` to prevent data leaks.
import { createApiClient } from "./client";
import { useAllPlugins } from "./plugins";

export const defaultClient = createApiClient();
useAllPlugins(defaultClient);

export const clientApi = createApi(defaultClient);


// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
