// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  BusinessUnitDTO,
  BusinessUnitPageResponse,
  BusinessUnitBusinessunitListParams,
  BusinessUnitBusinessunitListResponse,
  BusinessUnitBusinessunitCreatePayload,
  BusinessUnitBusinessunitCreateResponse,
  BusinessUnitBusinessunitDeleteResponse,
  BusinessUnitBusinessunitGetResponse,
  BusinessUnitBusinessunitUpdatePayload,
  BusinessUnitBusinessunitUpdateResponse,
} from "./businessunit.types";
import {
  BusinessUnitBusinessunitListResponseSchema,
  BusinessUnitBusinessunitCreateResponseSchema,
  BusinessUnitBusinessunitGetResponseSchema,
  BusinessUnitBusinessunitUpdateResponseSchema,
} from "./businessunit.types";

export type {
  BusinessUnitDTO,
  BusinessUnitPageResponse,
  BusinessUnitBusinessunitListParams,
  BusinessUnitBusinessunitListResponse,
  BusinessUnitBusinessunitCreatePayload,
  BusinessUnitBusinessunitCreateResponse,
  BusinessUnitBusinessunitDeleteResponse,
  BusinessUnitBusinessunitGetResponse,
  BusinessUnitBusinessunitUpdatePayload,
  BusinessUnitBusinessunitUpdateResponse,
};

export class BusinessUnitService extends BaseService<"businessunit"> {
  constructor(client: ApiClient) {
    super(client, "businessunit");
  }

  /**
   * businessunit-list
   * List business units
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `BusinessUnitBusinessunitListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.businessunit.businessunitList(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public businessunitList(
    params?: BusinessUnitBusinessunitListParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<
    ApiResult<BusinessUnitBusinessunitListResponse, AppApiErrorData>
  > {
    return this.client.get<
      BusinessUnitBusinessunitListResponse,
      AppApiErrorData
    >(`/api/v1/business-units`, {
      ...this.withSignal(config),
      params,
      zodSchema: BusinessUnitBusinessunitListResponseSchema,
    });
  }

  /**
   * businessunit-create
   * Create a business unit

   * @param payload - Request body (`BusinessUnitBusinessunitCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `BusinessUnitBusinessunitCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.businessunit.businessunitCreate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public businessunitCreate(
    payload: BusinessUnitBusinessunitCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<BusinessUnitBusinessunitCreateResponse, AppApiErrorData>
  > {
    return this.client.post<
      BusinessUnitBusinessunitCreateResponse,
      AppApiErrorData
    >(`/api/v1/business-units`, payload, {
      ...this.withSignal(config),
      zodSchema: BusinessUnitBusinessunitCreateResponseSchema,
    });
  }

  /**
   * businessunit-delete
   * Delete a business unit
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.businessunit.businessunitDelete(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public businessunitDelete(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/business-units/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * businessunit-get
   * Get a business unit by ID
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `BusinessUnitBusinessunitGetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.businessunit.businessunitGet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public businessunitGet(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<BusinessUnitBusinessunitGetResponse, AppApiErrorData>
  > {
    return this.client.get<
      BusinessUnitBusinessunitGetResponse,
      AppApiErrorData
    >(`/api/v1/business-units/${id}`, {
      ...this.withSignal(config),
      zodSchema: BusinessUnitBusinessunitGetResponseSchema,
    });
  }

  /**
   * businessunit-update
   * Update a business unit
   * @param id - Path parameter

   * @param payload - Request body (`BusinessUnitBusinessunitUpdatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `BusinessUnitBusinessunitUpdateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.businessunit.businessunitUpdate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public businessunitUpdate(
    id: string | number,
    payload: BusinessUnitBusinessunitUpdatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<BusinessUnitBusinessunitUpdateResponse, AppApiErrorData>
  > {
    return this.client.put<
      BusinessUnitBusinessunitUpdateResponse,
      AppApiErrorData
    >(`/api/v1/business-units/${id}`, payload, {
      ...this.withSignal(config),
      zodSchema: BusinessUnitBusinessunitUpdateResponseSchema,
    });
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
