// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Shared Models --
export const SuccessResponseSchema = z.object({
  message: z.string(),
});
export type SuccessResponse = z.infer<typeof SuccessResponseSchema>;

// -- Specific Models for businessunit --
export const BusinessUnitDTOSchema = z.object({
  $schema: z.string().optional(),
  code: z.string(),
  id: z.number().optional(),
  name: z.string(),
});
export type BusinessUnitDTO = z.infer<typeof BusinessUnitDTOSchema>;

export const BusinessUnitPageResponseSchema = z.object({
  items: z.any(),
  page: z.number(),
  size: z.number(),
  total: z.number(),
  total_pages: z.number(),
});
export type BusinessUnitPageResponse = z.infer<
  typeof BusinessUnitPageResponseSchema
>;

// -- Request & Response Types --

export type BusinessUnitBusinessunitListParams = {
  page?: number;
  size?: number;
  search?: string;
  sort_by?: string;
  sort_order?: string;
};

export const BusinessUnitBusinessunitListResponseSchema =
  BusinessUnitPageResponseSchema;
export type BusinessUnitBusinessunitListResponse = z.infer<
  typeof BusinessUnitBusinessunitListResponseSchema
>;

export type BusinessUnitBusinessunitCreatePayload = BusinessUnitDTO;

export const BusinessUnitBusinessunitCreateResponseSchema =
  BusinessUnitDTOSchema;
export type BusinessUnitBusinessunitCreateResponse = z.infer<
  typeof BusinessUnitBusinessunitCreateResponseSchema
>;

export const BusinessUnitBusinessunitDeleteResponseSchema =
  SuccessResponseSchema;
export type BusinessUnitBusinessunitDeleteResponse = z.infer<
  typeof BusinessUnitBusinessunitDeleteResponseSchema
>;

export const BusinessUnitBusinessunitGetResponseSchema = BusinessUnitDTOSchema;
export type BusinessUnitBusinessunitGetResponse = z.infer<
  typeof BusinessUnitBusinessunitGetResponseSchema
>;

export type BusinessUnitBusinessunitUpdatePayload = BusinessUnitDTO;

export const BusinessUnitBusinessunitUpdateResponseSchema =
  SuccessResponseSchema;
export type BusinessUnitBusinessunitUpdateResponse = z.infer<
  typeof BusinessUnitBusinessunitUpdateResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
