// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  CustomerDTO,
  CustomerPageResponse,
  CustomerCustomerListParams,
  CustomerCustomerListResponse,
  CustomerCustomerCreatePayload,
  CustomerCustomerCreateResponse,
  CustomerCustomerDeleteResponse,
  CustomerCustomerGetResponse,
  CustomerCustomerUpdatePayload,
  CustomerCustomerUpdateResponse,
} from "./customer.types";
import {
  CustomerCustomerListResponseSchema,
  CustomerCustomerCreateResponseSchema,
  CustomerCustomerGetResponseSchema,
  CustomerCustomerUpdateResponseSchema,
} from "./customer.types";

export type {
  CustomerDTO,
  CustomerPageResponse,
  CustomerCustomerListParams,
  CustomerCustomerListResponse,
  CustomerCustomerCreatePayload,
  CustomerCustomerCreateResponse,
  CustomerCustomerDeleteResponse,
  CustomerCustomerGetResponse,
  CustomerCustomerUpdatePayload,
  CustomerCustomerUpdateResponse,
};

export class CustomerService extends BaseService<"customer"> {
  constructor(client: ApiClient) {
    super(client, "customer");
  }

  /**
   * customer-list
   * List customers
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `CustomerCustomerListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.customer.customerList(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public customerList(
    params?: CustomerCustomerListParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<
    ApiResult<CustomerCustomerListResponse, AppApiErrorData>
  > {
    return this.client.get<CustomerCustomerListResponse, AppApiErrorData>(
      `/api/v1/customers`,
      {
        ...this.withSignal(config),
        params,
        zodSchema: CustomerCustomerListResponseSchema,
      },
    );
  }

  /**
   * customer-create
   * Create a customer

   * @param payload - Request body (`CustomerCustomerCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `CustomerCustomerCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.customer.customerCreate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public customerCreate(
    payload: CustomerCustomerCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<CustomerCustomerCreateResponse, AppApiErrorData>
  > {
    return this.client.post<CustomerCustomerCreateResponse, AppApiErrorData>(
      `/api/v1/customers`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: CustomerCustomerCreateResponseSchema,
      },
    );
  }

  /**
   * customer-delete
   * Delete a customer
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.customer.customerDelete(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public customerDelete(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/customers/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * customer-get
   * Get a customer by ID
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `CustomerCustomerGetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.customer.customerGet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public customerGet(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<CustomerCustomerGetResponse, AppApiErrorData>
  > {
    return this.client.get<CustomerCustomerGetResponse, AppApiErrorData>(
      `/api/v1/customers/${id}`,
      {
        ...this.withSignal(config),
        zodSchema: CustomerCustomerGetResponseSchema,
      },
    );
  }

  /**
   * customer-update
   * Update a customer
   * @param id - Path parameter

   * @param payload - Request body (`CustomerCustomerUpdatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `CustomerCustomerUpdateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.customer.customerUpdate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public customerUpdate(
    id: string | number,
    payload: CustomerCustomerUpdatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<CustomerCustomerUpdateResponse, AppApiErrorData>
  > {
    return this.client.put<CustomerCustomerUpdateResponse, AppApiErrorData>(
      `/api/v1/customers/${id}`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: CustomerCustomerUpdateResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
