// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Shared Models --
export const SuccessResponseSchema = z.object({
  message: z.string(),
});
export type SuccessResponse = z.infer<typeof SuccessResponseSchema>;

// -- Specific Models for customer --
export const CustomerDTOSchema = z.object({
  $schema: z.string().optional(),
  business_unit_code: z.string(),
  id: z.number().optional(),
  name: z.string(),
  phone: z.string(),
});
export type CustomerDTO = z.infer<typeof CustomerDTOSchema>;

export const CustomerPageResponseSchema = z.object({
  items: z.any(),
  page: z.number(),
  size: z.number(),
  total: z.number(),
  total_pages: z.number(),
});
export type CustomerPageResponse = z.infer<typeof CustomerPageResponseSchema>;

// -- Request & Response Types --

export type CustomerCustomerListParams = {
  page?: number;
  size?: number;
  search?: string;
  sort_by?: string;
  sort_order?: string;
};

export const CustomerCustomerListResponseSchema = CustomerPageResponseSchema;
export type CustomerCustomerListResponse = z.infer<
  typeof CustomerCustomerListResponseSchema
>;

export type CustomerCustomerCreatePayload = CustomerDTO;

export const CustomerCustomerCreateResponseSchema = CustomerDTOSchema;
export type CustomerCustomerCreateResponse = z.infer<
  typeof CustomerCustomerCreateResponseSchema
>;

export const CustomerCustomerDeleteResponseSchema = SuccessResponseSchema;
export type CustomerCustomerDeleteResponse = z.infer<
  typeof CustomerCustomerDeleteResponseSchema
>;

export const CustomerCustomerGetResponseSchema = CustomerDTOSchema;
export type CustomerCustomerGetResponse = z.infer<
  typeof CustomerCustomerGetResponseSchema
>;

export type CustomerCustomerUpdatePayload = CustomerDTO;

export const CustomerCustomerUpdateResponseSchema = SuccessResponseSchema;
export type CustomerCustomerUpdateResponse = z.infer<
  typeof CustomerCustomerUpdateResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
