// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  DispatchBody,
  DispatchCreatePayload,
  DispatchCreateResponse,
} from "./dispatch.types";
import { DispatchCreateResponseSchema } from "./dispatch.types";

export type { DispatchBody, DispatchCreatePayload, DispatchCreateResponse };

export class DispatchService extends BaseService<"dispatch"> {
  constructor(client: ApiClient) {
    super(client, "dispatch");
  }

  /**
   * dispatch:create
   * Dispatch Parcel onto Truck

   * @param payload - Request body (`DispatchCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `DispatchCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.dispatch.create(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public create(
    payload: DispatchCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<DispatchCreateResponse, AppApiErrorData>> {
    return this.client.post<DispatchCreateResponse, AppApiErrorData>(
      `/api/v1/dispatch`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: DispatchCreateResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
