// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for dispatch --
export const DispatchBodySchema = z.object({
  $schema: z.string().optional(),
  parcelId: z.number(),
  truckId: z.number(),
});
export type DispatchBody = z.infer<typeof DispatchBodySchema>;

// -- Request & Response Types --
export type DispatchCreatePayload = DispatchBody;

export const DispatchCreateResponseSchema = z.any();
export type DispatchCreateResponse = z.infer<
  typeof DispatchCreateResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
