// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for fleet --
export const CreateTruckBodySchema = z.object({
  $schema: z.string().optional(),
  licensePlate: z.string(),
  maxCapacity: z.number(),
});
export type CreateTruckBody = z.infer<typeof CreateTruckBodySchema>;

export const DeleteMessageSchema = z.object({
  message: z.string(),
});
export type DeleteMessage = z.infer<typeof DeleteMessageSchema>;

export const PageResponseTruckResponseSchema = z.object({
  items: z.any(),
  page: z.number(),
  size: z.number(),
  total_items: z.number(),
  total_pages: z.number(),
});
export type PageResponseTruckResponse = z.infer<
  typeof PageResponseTruckResponseSchema
>;

export const TruckResponseSchema = z.object({
  currentLoad: z.number(),
  id: z.number(),
  licensePlate: z.string(),
  maxCapacity: z.number(),
});
export type TruckResponse = z.infer<typeof TruckResponseSchema>;

export const UpdateTruckBodySchema = z.object({
  $schema: z.string().optional(),
  currentLoad: z.number(),
  licensePlate: z.string(),
  maxCapacity: z.number(),
});
export type UpdateTruckBody = z.infer<typeof UpdateTruckBodySchema>;

// -- Request & Response Types --

export type FleetListParams = {
  page?: number;
  size?: number;
  sort_by?: string;
  sort_order?: "asc" | "desc";
  search?: string;
  min_capacity?: number;
};

export const FleetListResponseSchema = PageResponseTruckResponseSchema;
export type FleetListResponse = z.infer<typeof FleetListResponseSchema>;

export type FleetCreatePayload = CreateTruckBody;

export const FleetCreateResponseSchema = TruckResponseSchema;
export type FleetCreateResponse = z.infer<typeof FleetCreateResponseSchema>;

export const FleetDeleteResponseSchema = DeleteMessageSchema;
export type FleetDeleteResponse = z.infer<typeof FleetDeleteResponseSchema>;

export const FleetGetResponseSchema = TruckResponseSchema;
export type FleetGetResponse = z.infer<typeof FleetGetResponseSchema>;

export type FleetUpdatePayload = UpdateTruckBody;

export const FleetUpdateResponseSchema = TruckResponseSchema;
export type FleetUpdateResponse = z.infer<typeof FleetUpdateResponseSchema>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
