// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  CreateTruckBody,
  DeleteMessage,
  PageResponseTruckResponse,
  TruckResponse,
  UpdateTruckBody,
  FleetListParams,
  FleetListResponse,
  FleetCreatePayload,
  FleetCreateResponse,
  FleetDeleteResponse,
  FleetGetResponse,
  FleetUpdatePayload,
  FleetUpdateResponse,
} from "./fleet.types";
import {
  FleetListResponseSchema,
  FleetCreateResponseSchema,
  FleetGetResponseSchema,
  FleetUpdateResponseSchema,
} from "./fleet.types";

export type {
  CreateTruckBody,
  DeleteMessage,
  PageResponseTruckResponse,
  TruckResponse,
  UpdateTruckBody,
  FleetListParams,
  FleetListResponse,
  FleetCreatePayload,
  FleetCreateResponse,
  FleetDeleteResponse,
  FleetGetResponse,
  FleetUpdatePayload,
  FleetUpdateResponse,
};

export class FleetService extends BaseService<"fleet"> {
  constructor(client: ApiClient) {
    super(client, "fleet");
  }

  /**
   * fleet:list
   * List Trucks
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FleetListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fleet.list(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public list(
    params?: FleetListParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<ApiResult<FleetListResponse, AppApiErrorData>> {
    return this.client.get<FleetListResponse, AppApiErrorData>(
      `/api/v1/trucks`,
      {
        ...this.withSignal(config),
        params,
        zodSchema: FleetListResponseSchema,
      },
    );
  }

  /**
   * fleet:create
   * Create Truck

   * @param payload - Request body (`FleetCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FleetCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fleet.create(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public create(
    payload: FleetCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<FleetCreateResponse, AppApiErrorData>> {
    return this.client.post<FleetCreateResponse, AppApiErrorData>(
      `/api/v1/trucks`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: FleetCreateResponseSchema,
      },
    );
  }

  /**
   * fleet:delete
   * Delete Truck
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fleet.delete(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public delete(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/trucks/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * fleet:get
   * Get Truck
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FleetGetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fleet.get(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public get(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<FleetGetResponse, AppApiErrorData>> {
    return this.client.get<FleetGetResponse, AppApiErrorData>(
      `/api/v1/trucks/${id}`,
      {
        ...this.withSignal(config),
        zodSchema: FleetGetResponseSchema,
      },
    );
  }

  /**
   * fleet:update
   * Update Truck
   * @param id - Path parameter

   * @param payload - Request body (`FleetUpdatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FleetUpdateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fleet.update(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public update(
    id: string | number,
    payload: FleetUpdatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<FleetUpdateResponse, AppApiErrorData>> {
    return this.client.put<FleetUpdateResponse, AppApiErrorData>(
      `/api/v1/trucks/${id}`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: FleetUpdateResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
