// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  ListPendingFulfillmentsResponse,
  ProcessFulfillmentRequestBody,
  ProcessFulfillmentResponse,
  ReceiveMarketplaceOrderBody,
  ReceiveMarketplaceOrderResponse,
  FulfillmentFulfillmentListPendingResponse,
  FulfillmentFulfillmentProcessPayload,
  FulfillmentFulfillmentProcessResponse,
  FulfillmentFulfillmentWebhookPayload,
  FulfillmentFulfillmentWebhookResponse,
} from "./fulfillment.types";
import {
  FulfillmentFulfillmentListPendingResponseSchema,
  FulfillmentFulfillmentProcessResponseSchema,
  FulfillmentFulfillmentWebhookResponseSchema,
} from "./fulfillment.types";

export type {
  ListPendingFulfillmentsResponse,
  ProcessFulfillmentRequestBody,
  ProcessFulfillmentResponse,
  ReceiveMarketplaceOrderBody,
  ReceiveMarketplaceOrderResponse,
  FulfillmentFulfillmentListPendingResponse,
  FulfillmentFulfillmentProcessPayload,
  FulfillmentFulfillmentProcessResponse,
  FulfillmentFulfillmentWebhookPayload,
  FulfillmentFulfillmentWebhookResponse,
};

export class FulfillmentService extends BaseService<"fulfillment"> {
  constructor(client: ApiClient) {
    super(client, "fulfillment");
  }

  /**
   * fulfillment-list-pending
   * List all pending marketplace orders awaiting grouping
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FulfillmentFulfillmentListPendingResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fulfillment.fulfillmentListPending(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public fulfillmentListPending(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<FulfillmentFulfillmentListPendingResponse, AppApiErrorData>
  > {
    return this.client.get<
      FulfillmentFulfillmentListPendingResponse,
      AppApiErrorData
    >(`/api/v1/fulfillments/pending`, {
      ...this.withSignal(config),
      zodSchema: FulfillmentFulfillmentListPendingResponseSchema,
    });
  }

  /**
   * fulfillment-process
   * Group selected marketplace orders by carrier and generate SaleOrders

   * @param payload - Request body (`FulfillmentFulfillmentProcessPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FulfillmentFulfillmentProcessResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fulfillment.fulfillmentProcess(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public fulfillmentProcess(
    payload: FulfillmentFulfillmentProcessPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<FulfillmentFulfillmentProcessResponse, AppApiErrorData>
  > {
    return this.client.post<
      FulfillmentFulfillmentProcessResponse,
      AppApiErrorData
    >(`/api/v1/fulfillments/process`, payload, {
      ...this.withSignal(config),
      zodSchema: FulfillmentFulfillmentProcessResponseSchema,
    });
  }

  /**
   * fulfillment-webhook
   * Webhook receiver for marketplace orders (Shopee/Lazada)

   * @param payload - Request body (`FulfillmentFulfillmentWebhookPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FulfillmentFulfillmentWebhookResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fulfillment.fulfillmentWebhook(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public fulfillmentWebhook(
    payload: FulfillmentFulfillmentWebhookPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<FulfillmentFulfillmentWebhookResponse, AppApiErrorData>
  > {
    return this.client.post<
      FulfillmentFulfillmentWebhookResponse,
      AppApiErrorData
    >(`/api/v1/webhooks/marketplace-orders`, payload, {
      ...this.withSignal(config),
      zodSchema: FulfillmentFulfillmentWebhookResponseSchema,
    });
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
