// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for fulfillment --
export const FulfillmentItemResponseSchema = z.object({
  currency: z.string().optional(),
  item_code: z.string().optional(),
  quantity: z.number().optional(),
  unit_price: z.number().optional(),
  uom: z.string().optional(),
});
export type FulfillmentItemResponse = z.infer<
  typeof FulfillmentItemResponseSchema
>;

export const FulfillmentRequestResponseSchema = z.object({
  business_unit_code: z.string().optional(),
  carrier: z.string().optional(),
  customer_code: z.string().optional(),
  id: z.string().optional(),
  items: z.array(FulfillmentItemResponseSchema).optional(),
  marketplace: z.string().optional(),
  marketplace_order_id: z.string().optional(),
  sale_order_id: z.string().optional(),
  status: z.string().optional(),
});
export type FulfillmentRequestResponse = z.infer<
  typeof FulfillmentRequestResponseSchema
>;

export const ListFulfillmentsPageResponseSchema = z.object({
  items: z.array(FulfillmentRequestResponseSchema).optional(),
  page: z.number().optional(),
  size: z.number().optional(),
  total: z.number().optional(),
  total_pages: z.number().optional(),
});
export type ListFulfillmentsPageResponse = z.infer<
  typeof ListFulfillmentsPageResponseSchema
>;

export const ProcessFulfillmentRequestBodySchema = z.object({
  ids: z.array(z.string()),
});
export type ProcessFulfillmentRequestBody = z.infer<
  typeof ProcessFulfillmentRequestBodySchema
>;

export const ProcessFulfillmentResponseSchema = z.object({
  generated_sale_order_ids: z.array(z.string()).optional(),
});
export type ProcessFulfillmentResponse = z.infer<
  typeof ProcessFulfillmentResponseSchema
>;

export const ReceiveItemDTOSchema = z.object({
  currency: z.string().optional(),
  item_code: z.string(),
  quantity: z.number(),
  unit_price: z.number(),
  uom: z.string().optional(),
});
export type ReceiveItemDTO = z.infer<typeof ReceiveItemDTOSchema>;

export const ReceiveMarketplaceOrderBodySchema = z.object({
  business_unit_code: z.string(),
  carrier: z.string(),
  customer_code: z.string(),
  items: z.array(ReceiveItemDTOSchema),
  marketplace: z.string(),
  marketplace_order_id: z.string(),
});
export type ReceiveMarketplaceOrderBody = z.infer<
  typeof ReceiveMarketplaceOrderBodySchema
>;

export const ReceiveMarketplaceOrderResponseSchema = z.object({
  id: z.string().optional(),
});
export type ReceiveMarketplaceOrderResponse = z.infer<
  typeof ReceiveMarketplaceOrderResponseSchema
>;

// -- Request & Response Types --

export const FulfillmentFulfillmentListResponseSchema =
  ListFulfillmentsPageResponseSchema;
export type FulfillmentFulfillmentListResponse = z.infer<
  typeof FulfillmentFulfillmentListResponseSchema
>;

export type FulfillmentFulfillmentProcessPayload =
  ProcessFulfillmentRequestBody;

export const FulfillmentFulfillmentProcessResponseSchema =
  ProcessFulfillmentResponseSchema;
export type FulfillmentFulfillmentProcessResponse = z.infer<
  typeof FulfillmentFulfillmentProcessResponseSchema
>;

export type FulfillmentFulfillmentReceiveWebhookPayload =
  ReceiveMarketplaceOrderBody;

export const FulfillmentFulfillmentReceiveWebhookResponseSchema =
  ReceiveMarketplaceOrderResponseSchema;
export type FulfillmentFulfillmentReceiveWebhookResponse = z.infer<
  typeof FulfillmentFulfillmentReceiveWebhookResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
