// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for fulfillment --
export const ListPendingFulfillmentsResponseSchema = z.object({
  items: z.any(),
});
export type ListPendingFulfillmentsResponse = z.infer<
  typeof ListPendingFulfillmentsResponseSchema
>;

export const ProcessFulfillmentRequestBodySchema = z.object({
  $schema: z.string().optional(),
  ids: z.any(),
});
export type ProcessFulfillmentRequestBody = z.infer<
  typeof ProcessFulfillmentRequestBodySchema
>;

export const ProcessFulfillmentResponseSchema = z.object({
  generated_sale_order_ids: z.any(),
});
export type ProcessFulfillmentResponse = z.infer<
  typeof ProcessFulfillmentResponseSchema
>;

export const ReceiveMarketplaceOrderBodySchema = z.object({
  $schema: z.string().optional(),
  business_unit_code: z.string(),
  carrier: z.string(),
  customer_code: z.string(),
  items: z.any(),
  marketplace: z.string(),
  marketplace_order_id: z.string(),
});
export type ReceiveMarketplaceOrderBody = z.infer<
  typeof ReceiveMarketplaceOrderBodySchema
>;

export const ReceiveMarketplaceOrderResponseSchema = z.object({
  id: z.number(),
});
export type ReceiveMarketplaceOrderResponse = z.infer<
  typeof ReceiveMarketplaceOrderResponseSchema
>;

// -- Request & Response Types --

export const FulfillmentFulfillmentListPendingResponseSchema =
  ListPendingFulfillmentsResponseSchema;
export type FulfillmentFulfillmentListPendingResponse = z.infer<
  typeof FulfillmentFulfillmentListPendingResponseSchema
>;

export type FulfillmentFulfillmentProcessPayload =
  ProcessFulfillmentRequestBody;

export const FulfillmentFulfillmentProcessResponseSchema =
  ProcessFulfillmentResponseSchema;
export type FulfillmentFulfillmentProcessResponse = z.infer<
  typeof FulfillmentFulfillmentProcessResponseSchema
>;

export type FulfillmentFulfillmentWebhookPayload = ReceiveMarketplaceOrderBody;

export const FulfillmentFulfillmentWebhookResponseSchema =
  ReceiveMarketplaceOrderResponseSchema;
export type FulfillmentFulfillmentWebhookResponse = z.infer<
  typeof FulfillmentFulfillmentWebhookResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
