// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  FulfillmentItemResponse,
  FulfillmentRequestResponse,
  ListFulfillmentsPageResponse,
  ProcessFulfillmentRequestBody,
  ProcessFulfillmentResponse,
  ReceiveItemDTO,
  ReceiveMarketplaceOrderBody,
  ReceiveMarketplaceOrderResponse,
  FulfillmentFulfillmentListResponse,
  FulfillmentFulfillmentProcessPayload,
  FulfillmentFulfillmentProcessResponse,
  FulfillmentFulfillmentReceiveWebhookPayload,
  FulfillmentFulfillmentReceiveWebhookResponse,
} from "./fulfillment.types";
import {
  FulfillmentFulfillmentListResponseSchema,
  FulfillmentFulfillmentProcessResponseSchema,
  FulfillmentFulfillmentReceiveWebhookResponseSchema,
} from "./fulfillment.types";

export type {
  FulfillmentItemResponse,
  FulfillmentRequestResponse,
  ListFulfillmentsPageResponse,
  ProcessFulfillmentRequestBody,
  ProcessFulfillmentResponse,
  ReceiveItemDTO,
  ReceiveMarketplaceOrderBody,
  ReceiveMarketplaceOrderResponse,
  FulfillmentFulfillmentListResponse,
  FulfillmentFulfillmentProcessPayload,
  FulfillmentFulfillmentProcessResponse,
  FulfillmentFulfillmentReceiveWebhookPayload,
  FulfillmentFulfillmentReceiveWebhookResponse,
};

export class FulfillmentService extends BaseService<"fulfillment"> {
  constructor(client: ApiClient) {
    super(client, "fulfillment");
  }

  /**
   * fulfillmentList
   * List returns all fulfillment requests, optionally filtered by status and other query params
   * Requires permission: fulfillment:list
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FulfillmentFulfillmentListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fulfillment.fulfillmentList(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public fulfillmentList(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<FulfillmentFulfillmentListResponse, AppApiErrorData>
  > {
    return this.client.get<FulfillmentFulfillmentListResponse, AppApiErrorData>(
      `/api/v1/fulfillments`,
      {
        ...this.withSignal(config),
        zodSchema: FulfillmentFulfillmentListResponseSchema,
      },
    );
  }

  /**
   * fulfillmentProcess
   * Process handles user selection to group pending orders by carrier and generate SOs
   * Requires permission: fulfillment:process

   * @param payload - Request body (`FulfillmentFulfillmentProcessPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FulfillmentFulfillmentProcessResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fulfillment.fulfillmentProcess(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public fulfillmentProcess(
    payload: FulfillmentFulfillmentProcessPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<FulfillmentFulfillmentProcessResponse, AppApiErrorData>
  > {
    return this.client.post<
      FulfillmentFulfillmentProcessResponse,
      AppApiErrorData
    >(`/api/v1/fulfillments/process`, payload, {
      ...this.withSignal(config),
      zodSchema: FulfillmentFulfillmentProcessResponseSchema,
    });
  }

  /**
   * fulfillmentReceiveWebhook
   * ReceiveWebhook handles incoming marketplace orders from Shopee/Lazada webhooks
   * Requires permission: fulfillment:process

   * @param payload - Request body (`FulfillmentFulfillmentReceiveWebhookPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `FulfillmentFulfillmentReceiveWebhookResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.fulfillment.fulfillmentReceiveWebhook(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public fulfillmentReceiveWebhook(
    payload: FulfillmentFulfillmentReceiveWebhookPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<FulfillmentFulfillmentReceiveWebhookResponse, AppApiErrorData>
  > {
    return this.client.post<
      FulfillmentFulfillmentReceiveWebhookResponse,
      AppApiErrorData
    >(`/api/v1/webhooks/marketplace-orders`, payload, {
      ...this.withSignal(config),
      zodSchema: FulfillmentFulfillmentReceiveWebhookResponseSchema,
    });
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
