// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  HealthResponseBody,
  HealthLivenessResponse,
  HealthReadinessResponse,
} from "./health.types";
import {
  HealthLivenessResponseSchema,
  HealthReadinessResponseSchema,
} from "./health.types";

export type {
  HealthResponseBody,
  HealthLivenessResponse,
  HealthReadinessResponse,
};

export class HealthService extends BaseService<"health"> {
  constructor(client: ApiClient) {
    super(client, "health");
  }

  /**
   * liveness
   * Liveness Probe
   * Returns 200 OK if the HTTP server is running.
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `HealthLivenessResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.health.liveness(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public liveness(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<HealthLivenessResponse, AppApiErrorData>> {
    return this.client.get<HealthLivenessResponse, AppApiErrorData>(
      `/healthz`,
      {
        ...this.withSignal(config),
        zodSchema: HealthLivenessResponseSchema,
      },
    );
  }

  /**
   * readiness
   * Readiness Probe
   * Returns 200 OK if the application is fully ready, including database connections.
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `HealthReadinessResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.health.readiness(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public readiness(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<HealthReadinessResponse, AppApiErrorData>> {
    return this.client.get<HealthReadinessResponse, AppApiErrorData>(
      `/readyz`,
      {
        ...this.withSignal(config),
        zodSchema: HealthReadinessResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
