// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for health --
export const HealthResponseBodySchema = z.object({
  $schema: z.string().optional(),
  status: z.string(),
  version: z.string(),
});
export type HealthResponseBody = z.infer<typeof HealthResponseBodySchema>;

// -- Request & Response Types --

export const HealthLivenessResponseSchema = HealthResponseBodySchema;
export type HealthLivenessResponse = z.infer<
  typeof HealthLivenessResponseSchema
>;

export const HealthReadinessResponseSchema = HealthResponseBodySchema;
export type HealthReadinessResponse = z.infer<
  typeof HealthReadinessResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
