// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  HealthHealthLivenessResponse,
  HealthHealthReadinessResponse,
} from "./health.types";
import {
  HealthHealthLivenessResponseSchema,
  HealthHealthReadinessResponseSchema,
} from "./health.types";

export type { HealthHealthLivenessResponse, HealthHealthReadinessResponse };

export class HealthService extends BaseService<"health"> {
  constructor(client: ApiClient) {
    super(client, "health");
  }

  /**
   * healthLiveness
   * Liveness
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `HealthHealthLivenessResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.health.healthLiveness(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public healthLiveness(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<HealthHealthLivenessResponse, AppApiErrorData>
  > {
    return this.client.get<HealthHealthLivenessResponse, AppApiErrorData>(
      `/healthz`,
      {
        ...this.withSignal(config),
        zodSchema: HealthHealthLivenessResponseSchema,
      },
    );
  }

  /**
   * healthReadiness
   * Readiness
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `HealthHealthReadinessResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.health.healthReadiness(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public healthReadiness(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<HealthHealthReadinessResponse, AppApiErrorData>
  > {
    return this.client.get<HealthHealthReadinessResponse, AppApiErrorData>(
      `/readyz`,
      {
        ...this.withSignal(config),
        zodSchema: HealthHealthReadinessResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
