// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Request & Response Types --

export const HealthHealthLivenessResponseSchema = z.record(z.string(), z.any());
export type HealthHealthLivenessResponse = z.infer<
  typeof HealthHealthLivenessResponseSchema
>;

export const HealthHealthReadinessResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type HealthHealthReadinessResponse = z.infer<
  typeof HealthHealthReadinessResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
