// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  ItemDTO,
  ItemPageResponse,
  ItemItemListParams,
  ItemItemListResponse,
  ItemItemCreatePayload,
  ItemItemCreateResponse,
  ItemItemDeleteResponse,
  ItemItemGetResponse,
  ItemItemUpdatePayload,
  ItemItemUpdateResponse,
} from "./item.types";
import {
  ItemItemListResponseSchema,
  ItemItemCreateResponseSchema,
  ItemItemGetResponseSchema,
  ItemItemUpdateResponseSchema,
} from "./item.types";

export type {
  ItemDTO,
  ItemPageResponse,
  ItemItemListParams,
  ItemItemListResponse,
  ItemItemCreatePayload,
  ItemItemCreateResponse,
  ItemItemDeleteResponse,
  ItemItemGetResponse,
  ItemItemUpdatePayload,
  ItemItemUpdateResponse,
};

export class ItemService extends BaseService<"item"> {
  constructor(client: ApiClient) {
    super(client, "item");
  }

  /**
   * item-list
   * List items
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `ItemItemListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.item.itemList(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public itemList(
    params?: ItemItemListParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<ApiResult<ItemItemListResponse, AppApiErrorData>> {
    return this.client.get<ItemItemListResponse, AppApiErrorData>(
      `/api/v1/items`,
      {
        ...this.withSignal(config),
        params,
        zodSchema: ItemItemListResponseSchema,
      },
    );
  }

  /**
   * item-create
   * Create an item

   * @param payload - Request body (`ItemItemCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `ItemItemCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.item.itemCreate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public itemCreate(
    payload: ItemItemCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<ItemItemCreateResponse, AppApiErrorData>> {
    return this.client.post<ItemItemCreateResponse, AppApiErrorData>(
      `/api/v1/items`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: ItemItemCreateResponseSchema,
      },
    );
  }

  /**
   * item-delete
   * Delete an item
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.item.itemDelete(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public itemDelete(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/items/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * item-get
   * Get an item by ID
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `ItemItemGetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.item.itemGet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public itemGet(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<ItemItemGetResponse, AppApiErrorData>> {
    return this.client.get<ItemItemGetResponse, AppApiErrorData>(
      `/api/v1/items/${id}`,
      {
        ...this.withSignal(config),
        zodSchema: ItemItemGetResponseSchema,
      },
    );
  }

  /**
   * item-update
   * Update an item
   * @param id - Path parameter

   * @param payload - Request body (`ItemItemUpdatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `ItemItemUpdateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.item.itemUpdate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public itemUpdate(
    id: string | number,
    payload: ItemItemUpdatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<ItemItemUpdateResponse, AppApiErrorData>> {
    return this.client.put<ItemItemUpdateResponse, AppApiErrorData>(
      `/api/v1/items/${id}`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: ItemItemUpdateResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
