// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Shared Models --
export const SuccessResponseSchema = z.object({
  message: z.string(),
});
export type SuccessResponse = z.infer<typeof SuccessResponseSchema>;

// -- Specific Models for item --
export const ItemDTOSchema = z.object({
  $schema: z.string().optional(),
  base_uom: z.string().optional(),
  business_unit_code: z.string(),
  code: z.string(),
  currency: z.string().optional(),
  default_price: z.number(),
  id: z.number().optional(),
  name: z.string(),
  packing_factors: z.record(z.string(), z.number()).optional(),
});
export type ItemDTO = z.infer<typeof ItemDTOSchema>;

export const ItemPageResponseSchema = z.object({
  items: z.any(),
  page: z.number(),
  size: z.number(),
  total: z.number(),
  total_pages: z.number(),
});
export type ItemPageResponse = z.infer<typeof ItemPageResponseSchema>;

// -- Request & Response Types --

export type ItemItemListParams = {
  page?: number;
  size?: number;
  search?: string;
  sort_by?: string;
  sort_order?: string;
};

export const ItemItemListResponseSchema = ItemPageResponseSchema;
export type ItemItemListResponse = z.infer<typeof ItemItemListResponseSchema>;

export type ItemItemCreatePayload = ItemDTO;

export const ItemItemCreateResponseSchema = ItemDTOSchema;
export type ItemItemCreateResponse = z.infer<
  typeof ItemItemCreateResponseSchema
>;

export const ItemItemDeleteResponseSchema = SuccessResponseSchema;
export type ItemItemDeleteResponse = z.infer<
  typeof ItemItemDeleteResponseSchema
>;

export const ItemItemGetResponseSchema = ItemDTOSchema;
export type ItemItemGetResponse = z.infer<typeof ItemItemGetResponseSchema>;

export type ItemItemUpdatePayload = ItemDTO;

export const ItemItemUpdateResponseSchema = SuccessResponseSchema;
export type ItemItemUpdateResponse = z.infer<
  typeof ItemItemUpdateResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
