// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  BusinessUnitDTO,
  BusinessUnitPageResponse,
  CustomerDTO,
  CustomerPageResponse,
  ItemDTO,
  ItemPageResponse,
  MasterMasterListBusinessUnitsResponse,
  MasterMasterCreateBusinessUnitPayload,
  MasterMasterCreateBusinessUnitResponse,
  MasterMasterDeleteBusinessUnitResponse,
  MasterMasterGetBusinessUnitResponse,
  MasterMasterUpdateBusinessUnitPayload,
  MasterMasterUpdateBusinessUnitResponse,
  MasterMasterListCustomersResponse,
  MasterMasterCreateCustomerPayload,
  MasterMasterCreateCustomerResponse,
  MasterMasterDeleteCustomerResponse,
  MasterMasterGetCustomerResponse,
  MasterMasterUpdateCustomerPayload,
  MasterMasterUpdateCustomerResponse,
  MasterMasterListItemsResponse,
  MasterMasterCreateItemPayload,
  MasterMasterCreateItemResponse,
  MasterMasterDeleteItemResponse,
  MasterMasterGetItemResponse,
  MasterMasterUpdateItemPayload,
  MasterMasterUpdateItemResponse,
} from "./master.types";
import {
  MasterMasterListBusinessUnitsResponseSchema,
  MasterMasterCreateBusinessUnitResponseSchema,
  MasterMasterGetBusinessUnitResponseSchema,
  MasterMasterUpdateBusinessUnitResponseSchema,
  MasterMasterListCustomersResponseSchema,
  MasterMasterCreateCustomerResponseSchema,
  MasterMasterGetCustomerResponseSchema,
  MasterMasterUpdateCustomerResponseSchema,
  MasterMasterListItemsResponseSchema,
  MasterMasterCreateItemResponseSchema,
  MasterMasterGetItemResponseSchema,
  MasterMasterUpdateItemResponseSchema,
} from "./master.types";

export type {
  BusinessUnitDTO,
  BusinessUnitPageResponse,
  CustomerDTO,
  CustomerPageResponse,
  ItemDTO,
  ItemPageResponse,
  MasterMasterListBusinessUnitsResponse,
  MasterMasterCreateBusinessUnitPayload,
  MasterMasterCreateBusinessUnitResponse,
  MasterMasterDeleteBusinessUnitResponse,
  MasterMasterGetBusinessUnitResponse,
  MasterMasterUpdateBusinessUnitPayload,
  MasterMasterUpdateBusinessUnitResponse,
  MasterMasterListCustomersResponse,
  MasterMasterCreateCustomerPayload,
  MasterMasterCreateCustomerResponse,
  MasterMasterDeleteCustomerResponse,
  MasterMasterGetCustomerResponse,
  MasterMasterUpdateCustomerPayload,
  MasterMasterUpdateCustomerResponse,
  MasterMasterListItemsResponse,
  MasterMasterCreateItemPayload,
  MasterMasterCreateItemResponse,
  MasterMasterDeleteItemResponse,
  MasterMasterGetItemResponse,
  MasterMasterUpdateItemPayload,
  MasterMasterUpdateItemResponse,
};

export class MasterService extends BaseService<"master"> {
  constructor(client: ApiClient) {
    super(client, "master");
  }

  /**
   * masterListBusinessUnits
   * ListBusinessUnits
   * Requires permission: businessunit:list
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterListBusinessUnitsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterListBusinessUnits(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterListBusinessUnits(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterListBusinessUnitsResponse, AppApiErrorData>
  > {
    return this.client.get<
      MasterMasterListBusinessUnitsResponse,
      AppApiErrorData
    >(`/api/v1/business-units`, {
      ...this.withSignal(config),
      zodSchema: MasterMasterListBusinessUnitsResponseSchema,
    });
  }

  /**
   * masterCreateBusinessUnit
   * CreateBusinessUnit
   * Requires permission: businessunit:create

   * @param payload - Request body (`MasterMasterCreateBusinessUnitPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterCreateBusinessUnitResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterCreateBusinessUnit(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterCreateBusinessUnit(
    payload: MasterMasterCreateBusinessUnitPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterCreateBusinessUnitResponse, AppApiErrorData>
  > {
    return this.client.post<
      MasterMasterCreateBusinessUnitResponse,
      AppApiErrorData
    >(`/api/v1/business-units`, payload, {
      ...this.withSignal(config),
      zodSchema: MasterMasterCreateBusinessUnitResponseSchema,
    });
  }

  /**
   * masterDeleteBusinessUnit
   * DeleteBusinessUnit
   * Requires permission: businessunit:delete
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterDeleteBusinessUnit(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterDeleteBusinessUnit(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/business-units/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * masterGetBusinessUnit
   * GetBusinessUnit
   * Requires permission: businessunit:get
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterGetBusinessUnitResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterGetBusinessUnit(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterGetBusinessUnit(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterGetBusinessUnitResponse, AppApiErrorData>
  > {
    return this.client.get<
      MasterMasterGetBusinessUnitResponse,
      AppApiErrorData
    >(`/api/v1/business-units/${id}`, {
      ...this.withSignal(config),
      zodSchema: MasterMasterGetBusinessUnitResponseSchema,
    });
  }

  /**
   * masterUpdateBusinessUnit
   * UpdateBusinessUnit
   * Requires permission: businessunit:update
   * @param id - Path parameter

   * @param payload - Request body (`MasterMasterUpdateBusinessUnitPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterUpdateBusinessUnitResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterUpdateBusinessUnit(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterUpdateBusinessUnit(
    id: string,
    payload: MasterMasterUpdateBusinessUnitPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterUpdateBusinessUnitResponse, AppApiErrorData>
  > {
    return this.client.put<
      MasterMasterUpdateBusinessUnitResponse,
      AppApiErrorData
    >(`/api/v1/business-units/${id}`, payload, {
      ...this.withSignal(config),
      zodSchema: MasterMasterUpdateBusinessUnitResponseSchema,
    });
  }

  /**
   * masterListCustomers
   * ListCustomers
   * Requires permission: customer:list
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterListCustomersResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterListCustomers(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterListCustomers(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterListCustomersResponse, AppApiErrorData>
  > {
    return this.client.get<MasterMasterListCustomersResponse, AppApiErrorData>(
      `/api/v1/customers`,
      {
        ...this.withSignal(config),
        zodSchema: MasterMasterListCustomersResponseSchema,
      },
    );
  }

  /**
   * masterCreateCustomer
   * CreateCustomer
   * Requires permission: customer:create

   * @param payload - Request body (`MasterMasterCreateCustomerPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterCreateCustomerResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterCreateCustomer(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterCreateCustomer(
    payload: MasterMasterCreateCustomerPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterCreateCustomerResponse, AppApiErrorData>
  > {
    return this.client.post<
      MasterMasterCreateCustomerResponse,
      AppApiErrorData
    >(`/api/v1/customers`, payload, {
      ...this.withSignal(config),
      zodSchema: MasterMasterCreateCustomerResponseSchema,
    });
  }

  /**
   * masterDeleteCustomer
   * DeleteCustomer
   * Requires permission: customer:delete
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterDeleteCustomer(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterDeleteCustomer(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/customers/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * masterGetCustomer
   * GetCustomer
   * Requires permission: customer:get
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterGetCustomerResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterGetCustomer(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterGetCustomer(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterGetCustomerResponse, AppApiErrorData>
  > {
    return this.client.get<MasterMasterGetCustomerResponse, AppApiErrorData>(
      `/api/v1/customers/${id}`,
      {
        ...this.withSignal(config),
        zodSchema: MasterMasterGetCustomerResponseSchema,
      },
    );
  }

  /**
   * masterUpdateCustomer
   * UpdateCustomer
   * Requires permission: customer:update
   * @param id - Path parameter

   * @param payload - Request body (`MasterMasterUpdateCustomerPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterUpdateCustomerResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterUpdateCustomer(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterUpdateCustomer(
    id: string,
    payload: MasterMasterUpdateCustomerPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterUpdateCustomerResponse, AppApiErrorData>
  > {
    return this.client.put<MasterMasterUpdateCustomerResponse, AppApiErrorData>(
      `/api/v1/customers/${id}`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: MasterMasterUpdateCustomerResponseSchema,
      },
    );
  }

  /**
   * masterListItems
   * ListItems
   * Requires permission: item:list
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterListItemsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterListItems(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterListItems(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterListItemsResponse, AppApiErrorData>
  > {
    return this.client.get<MasterMasterListItemsResponse, AppApiErrorData>(
      `/api/v1/items`,
      {
        ...this.withSignal(config),
        zodSchema: MasterMasterListItemsResponseSchema,
      },
    );
  }

  /**
   * masterCreateItem
   * CreateItem
   * Requires permission: item:create

   * @param payload - Request body (`MasterMasterCreateItemPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterCreateItemResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterCreateItem(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterCreateItem(
    payload: MasterMasterCreateItemPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterCreateItemResponse, AppApiErrorData>
  > {
    return this.client.post<MasterMasterCreateItemResponse, AppApiErrorData>(
      `/api/v1/items`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: MasterMasterCreateItemResponseSchema,
      },
    );
  }

  /**
   * masterDeleteItem
   * DeleteItem
   * Requires permission: item:delete
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterDeleteItem(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterDeleteItem(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/items/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * masterGetItem
   * GetItem
   * Requires permission: item:get
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterGetItemResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterGetItem(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterGetItem(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterGetItemResponse, AppApiErrorData>
  > {
    return this.client.get<MasterMasterGetItemResponse, AppApiErrorData>(
      `/api/v1/items/${id}`,
      {
        ...this.withSignal(config),
        zodSchema: MasterMasterGetItemResponseSchema,
      },
    );
  }

  /**
   * masterUpdateItem
   * UpdateItem
   * Requires permission: item:update
   * @param id - Path parameter

   * @param payload - Request body (`MasterMasterUpdateItemPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MasterMasterUpdateItemResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.master.masterUpdateItem(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public masterUpdateItem(
    id: string,
    payload: MasterMasterUpdateItemPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<MasterMasterUpdateItemResponse, AppApiErrorData>
  > {
    return this.client.put<MasterMasterUpdateItemResponse, AppApiErrorData>(
      `/api/v1/items/${id}`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: MasterMasterUpdateItemResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
