// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Shared Models --
export const SuccessResponseSchema = z.object({
  message: z.string().optional(),
});
export type SuccessResponse = z.infer<typeof SuccessResponseSchema>;

// -- Specific Models for master --
export const BusinessUnitDTOSchema = z.object({
  code: z.string(),
  id: z.string().optional(),
  name: z.string(),
});
export type BusinessUnitDTO = z.infer<typeof BusinessUnitDTOSchema>;

export const BusinessUnitPageResponseSchema = z.object({
  items: z.array(BusinessUnitDTOSchema).optional(),
  page: z.number().optional(),
  size: z.number().optional(),
  total: z.number().optional(),
  total_pages: z.number().optional(),
});
export type BusinessUnitPageResponse = z.infer<
  typeof BusinessUnitPageResponseSchema
>;

export const CustomerDTOSchema = z.object({
  business_unit_code: z.string(),
  code: z.string(),
  id: z.string().optional(),
  name: z.string(),
  phone: z.string(),
});
export type CustomerDTO = z.infer<typeof CustomerDTOSchema>;

export const CustomerPageResponseSchema = z.object({
  items: z.array(CustomerDTOSchema).optional(),
  page: z.number().optional(),
  size: z.number().optional(),
  total: z.number().optional(),
  total_pages: z.number().optional(),
});
export type CustomerPageResponse = z.infer<typeof CustomerPageResponseSchema>;

export const ItemDTOSchema = z.object({
  base_uom: z.string().optional(),
  business_unit_code: z.string(),
  code: z.string(),
  currency: z.string().optional(),
  default_price: z.number(),
  id: z.string().optional(),
  name: z.string(),
  packing_factors: z.record(z.string(), z.number()).optional(),
});
export type ItemDTO = z.infer<typeof ItemDTOSchema>;

export const ItemPageResponseSchema = z.object({
  items: z.array(ItemDTOSchema).optional(),
  page: z.number().optional(),
  size: z.number().optional(),
  total: z.number().optional(),
  total_pages: z.number().optional(),
});
export type ItemPageResponse = z.infer<typeof ItemPageResponseSchema>;

// -- Request & Response Types --

export const MasterMasterListBusinessUnitsResponseSchema =
  BusinessUnitPageResponseSchema;
export type MasterMasterListBusinessUnitsResponse = z.infer<
  typeof MasterMasterListBusinessUnitsResponseSchema
>;

export type MasterMasterCreateBusinessUnitPayload = any;

export const MasterMasterCreateBusinessUnitResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type MasterMasterCreateBusinessUnitResponse = z.infer<
  typeof MasterMasterCreateBusinessUnitResponseSchema
>;

export const MasterMasterGetBusinessUnitResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type MasterMasterGetBusinessUnitResponse = z.infer<
  typeof MasterMasterGetBusinessUnitResponseSchema
>;

export type MasterMasterUpdateBusinessUnitPayload = any;

export const MasterMasterUpdateBusinessUnitResponseSchema =
  SuccessResponseSchema;
export type MasterMasterUpdateBusinessUnitResponse = z.infer<
  typeof MasterMasterUpdateBusinessUnitResponseSchema
>;

export const MasterMasterDeleteBusinessUnitResponseSchema =
  SuccessResponseSchema;
export type MasterMasterDeleteBusinessUnitResponse = z.infer<
  typeof MasterMasterDeleteBusinessUnitResponseSchema
>;

export const MasterMasterListCustomersResponseSchema =
  CustomerPageResponseSchema;
export type MasterMasterListCustomersResponse = z.infer<
  typeof MasterMasterListCustomersResponseSchema
>;

export type MasterMasterCreateCustomerPayload = any;

export const MasterMasterCreateCustomerResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type MasterMasterCreateCustomerResponse = z.infer<
  typeof MasterMasterCreateCustomerResponseSchema
>;

export const MasterMasterGetCustomerResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type MasterMasterGetCustomerResponse = z.infer<
  typeof MasterMasterGetCustomerResponseSchema
>;

export type MasterMasterUpdateCustomerPayload = any;

export const MasterMasterUpdateCustomerResponseSchema = SuccessResponseSchema;
export type MasterMasterUpdateCustomerResponse = z.infer<
  typeof MasterMasterUpdateCustomerResponseSchema
>;

export const MasterMasterDeleteCustomerResponseSchema = SuccessResponseSchema;
export type MasterMasterDeleteCustomerResponse = z.infer<
  typeof MasterMasterDeleteCustomerResponseSchema
>;

export const MasterMasterListItemsResponseSchema = ItemPageResponseSchema;
export type MasterMasterListItemsResponse = z.infer<
  typeof MasterMasterListItemsResponseSchema
>;

export type MasterMasterCreateItemPayload = any;

export const MasterMasterCreateItemResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type MasterMasterCreateItemResponse = z.infer<
  typeof MasterMasterCreateItemResponseSchema
>;

export const MasterMasterGetItemResponseSchema = z.record(z.string(), z.any());
export type MasterMasterGetItemResponse = z.infer<
  typeof MasterMasterGetItemResponseSchema
>;

export type MasterMasterUpdateItemPayload = any;

export const MasterMasterUpdateItemResponseSchema = SuccessResponseSchema;
export type MasterMasterUpdateItemResponse = z.infer<
  typeof MasterMasterUpdateItemResponseSchema
>;

export const MasterMasterDeleteItemResponseSchema = SuccessResponseSchema;
export type MasterMasterDeleteItemResponse = z.infer<
  typeof MasterMasterDeleteItemResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
