// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for parcel --
export const BulkDispatchBodySchema = z.object({
  $schema: z.string().optional(),
  parcelIds: z.any(),
});
export type BulkDispatchBody = z.infer<typeof BulkDispatchBodySchema>;

export const CreateParcelBodySchema = z.object({
  $schema: z.string().optional(),
  trackingNumber: z.string(),
  weight: z.number(),
});
export type CreateParcelBody = z.infer<typeof CreateParcelBodySchema>;

export const ParcelResponseSchema = z.object({
  id: z.number(),
  status: z.string(),
  trackingNumber: z.string(),
  weight: z.number(),
});
export type ParcelResponse = z.infer<typeof ParcelResponseSchema>;

// -- Request & Response Types --
export type ParcelCreatePayload = CreateParcelBody;

export const ParcelCreateResponseSchema = ParcelResponseSchema;
export type ParcelCreateResponse = z.infer<typeof ParcelCreateResponseSchema>;

export type ParcelBulkDispatchPayload = BulkDispatchBody;

export const ParcelBulkDispatchResponseSchema = z.any();
export type ParcelBulkDispatchResponse = z.infer<
  typeof ParcelBulkDispatchResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
