// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  BulkDispatchBody,
  CreateParcelBody,
  ParcelResponse,
  ParcelCreatePayload,
  ParcelCreateResponse,
  ParcelBulkDispatchPayload,
  ParcelBulkDispatchResponse,
} from "./parcel.types";
import {
  ParcelCreateResponseSchema,
  ParcelBulkDispatchResponseSchema,
} from "./parcel.types";

export type {
  BulkDispatchBody,
  CreateParcelBody,
  ParcelResponse,
  ParcelCreatePayload,
  ParcelCreateResponse,
  ParcelBulkDispatchPayload,
  ParcelBulkDispatchResponse,
};

export class ParcelService extends BaseService<"parcel"> {
  constructor(client: ApiClient) {
    super(client, "parcel");
  }

  /**
   * parcel:create
   * Create Parcel

   * @param payload - Request body (`ParcelCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `ParcelCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.parcel.create(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public create(
    payload: ParcelCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<ParcelCreateResponse, AppApiErrorData>> {
    return this.client.post<ParcelCreateResponse, AppApiErrorData>(
      `/api/v1/parcels`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: ParcelCreateResponseSchema,
      },
    );
  }

  /**
   * parcel:bulk-dispatch
   * Bulk Dispatch Parcels (Standalone)

   * @param payload - Request body (`ParcelBulkDispatchPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `ParcelBulkDispatchResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.parcel.bulkDispatch(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public bulkDispatch(
    payload: ParcelBulkDispatchPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<ParcelBulkDispatchResponse, AppApiErrorData>> {
    return this.client.post<ParcelBulkDispatchResponse, AppApiErrorData>(
      `/api/v1/parcels/bulk-dispatch`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: ParcelBulkDispatchResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
