// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for saleorderschedule --
export const EventItemDTOSchema = z.object({
  currency: z.string().optional(),
  item_code: z.string(),
  quantity: z.number(),
  unit_price: z.number(),
});
export type EventItemDTO = z.infer<typeof EventItemDTOSchema>;

export const SaleOrderScheduleExecutionLogDetailResponseSchema = z.object({
  error_message: z.string().optional(),
  executed_at: z.string().optional(),
  generated_sale_order_id: z.string().optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional(),
  sale_order_schedule_id: z.string().optional(),
  status: z.string().optional(),
  trigger_source: z.string().optional(),
});
export type SaleOrderScheduleExecutionLogDetailResponse = z.infer<
  typeof SaleOrderScheduleExecutionLogDetailResponseSchema
>;

export const SaleOrderScheduleExecutionLogPageResponseSchema = z.object({
  items: z.array(SaleOrderScheduleExecutionLogDetailResponseSchema).optional(),
  page: z.number().optional(),
  size: z.number().optional(),
  total: z.number().optional(),
  total_pages: z.number().optional(),
});
export type SaleOrderScheduleExecutionLogPageResponse = z.infer<
  typeof SaleOrderScheduleExecutionLogPageResponseSchema
>;

export const SaleOrderScheduleItemResponseSchema = z.object({
  currency: z.string().optional(),
  item_code: z.string().optional(),
  quantity: z.number().optional(),
  unit_price: z.number().optional(),
});
export type SaleOrderScheduleItemResponse = z.infer<
  typeof SaleOrderScheduleItemResponseSchema
>;

export const SaleOrderScheduleResponseSchema = z.object({
  base_start_date: z.string().optional(),
  business_unit_code: z.string().optional(),
  cron_expression: z.string().optional(),
  customer_code: z.string().optional(),
  id: z.string().optional(),
  item_source_type: z.string().optional(),
  items: z.array(SaleOrderScheduleItemResponseSchema).optional(),
  last_error: z.string().optional(),
  last_run_at: z.string().optional(),
  last_run_status: z.string().optional(),
  next_run_at: z.string().optional(),
  order_date_offset_days: z.number().optional(),
  recurrence_interval_weeks: z.number().optional(),
  remark: z.string().optional(),
  retry_count: z.number().optional(),
  retry_limit: z.number().optional(),
  status: z.string().optional(),
  trigger_type: z.string().optional(),
});
export type SaleOrderScheduleResponse = z.infer<
  typeof SaleOrderScheduleResponseSchema
>;

export const SaleOrderSchedulePageResponseSchema = z.object({
  items: z.array(SaleOrderScheduleResponseSchema).optional(),
  page: z.number().optional(),
  size: z.number().optional(),
  total: z.number().optional(),
  total_pages: z.number().optional(),
});
export type SaleOrderSchedulePageResponse = z.infer<
  typeof SaleOrderSchedulePageResponseSchema
>;

export const ToggleSaleOrderScheduleBodySchema = z.object({
  active: z.boolean().optional(),
});
export type ToggleSaleOrderScheduleBody = z.infer<
  typeof ToggleSaleOrderScheduleBodySchema
>;

export const TriggerEventBodySchema = z.object({
  business_unit_code: z.string(),
  customer_code: z.string(),
  idempotency_key: z.string(),
  items: z.array(EventItemDTOSchema),
});
export type TriggerEventBody = z.infer<typeof TriggerEventBodySchema>;

// -- Request & Response Types --
export type SaleOrderScheduleSaleOrderScheduleTriggerEventPayload =
  TriggerEventBody;

export const SaleOrderScheduleSaleOrderScheduleTriggerEventResponseSchema =
  z.record(z.string(), z.any());
export type SaleOrderScheduleSaleOrderScheduleTriggerEventResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleTriggerEventResponseSchema
>;

export const SaleOrderScheduleSaleOrderScheduleListResponseSchema =
  SaleOrderSchedulePageResponseSchema;
export type SaleOrderScheduleSaleOrderScheduleListResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleListResponseSchema
>;

export type SaleOrderScheduleSaleOrderScheduleCreatePayload = any;

export const SaleOrderScheduleSaleOrderScheduleCreateResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderScheduleSaleOrderScheduleCreateResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleCreateResponseSchema
>;

export const SaleOrderScheduleSaleOrderScheduleGetResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderScheduleSaleOrderScheduleGetResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleGetResponseSchema
>;

export type SaleOrderScheduleSaleOrderScheduleUpdatePayload = any;

export const SaleOrderScheduleSaleOrderScheduleUpdateResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderScheduleSaleOrderScheduleUpdateResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleUpdateResponseSchema
>;

export const SaleOrderScheduleSaleOrderScheduleDeleteResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderScheduleSaleOrderScheduleDeleteResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleDeleteResponseSchema
>;

export const SaleOrderScheduleSaleOrderScheduleListLogsResponseSchema =
  SaleOrderScheduleExecutionLogPageResponseSchema;
export type SaleOrderScheduleSaleOrderScheduleListLogsResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleListLogsResponseSchema
>;

export const SaleOrderScheduleSaleOrderScheduleForceRunResponseSchema =
  z.record(z.string(), z.any());
export type SaleOrderScheduleSaleOrderScheduleForceRunResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleForceRunResponseSchema
>;

export type SaleOrderScheduleSaleOrderScheduleTogglePayload =
  ToggleSaleOrderScheduleBody;

export const SaleOrderScheduleSaleOrderScheduleToggleResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderScheduleSaleOrderScheduleToggleResponse = z.infer<
  typeof SaleOrderScheduleSaleOrderScheduleToggleResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
