// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for saleorder --
export const CreateSaleOrderBodySchema = z.object({
  $schema: z.string().optional(),
  business_unit_code: z.string(),
  customer_id: z.number(),
  items: z.any(),
  order_date: z.string(),
  remark: z.string(),
});
export type CreateSaleOrderBody = z.infer<typeof CreateSaleOrderBodySchema>;

export const SaleOrderResponseSchema = z.object({
  business_unit_code: z.string(),
  customer_id: z.number(),
  id: z.number(),
  items: z.any(),
  order_date: z.string(),
  order_no: z.string(),
  remark: z.string(),
  status: z.string(),
  total_price: z.number(),
});
export type SaleOrderResponse = z.infer<typeof SaleOrderResponseSchema>;

// -- Request & Response Types --
export type SaleOrderSaleorderCreatePayload = CreateSaleOrderBody;

export const SaleOrderSaleorderCreateResponseSchema = SaleOrderResponseSchema;
export type SaleOrderSaleorderCreateResponse = z.infer<
  typeof SaleOrderSaleorderCreateResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
