// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for saleorderschedule --
export const CreateSaleOrderScheduleBodySchema = z.object({
  $schema: z.string().optional(),
  base_start_date: z.string(),
  business_unit_code: z.string(),
  cron_expression: z.string(),
  customer_code: z.string(),
  item_source_type: z.string(),
  items: z.any(),
  order_date_offset_days: z.number(),
  recurrence_interval_weeks: z.number(),
  remark: z.string(),
  retry_limit: z.number(),
  trigger_type: z.string(),
});
export type CreateSaleOrderScheduleBody = z.infer<
  typeof CreateSaleOrderScheduleBodySchema
>;

export const SaleOrderScheduleExecutionLogPageResponseSchema = z.object({
  items: z.any(),
  page: z.number(),
  size: z.number(),
  total: z.number(),
  total_pages: z.number(),
});
export type SaleOrderScheduleExecutionLogPageResponse = z.infer<
  typeof SaleOrderScheduleExecutionLogPageResponseSchema
>;

export const SaleOrderSchedulePageResponseSchema = z.object({
  items: z.any(),
  page: z.number(),
  size: z.number(),
  total: z.number(),
  total_pages: z.number(),
});
export type SaleOrderSchedulePageResponse = z.infer<
  typeof SaleOrderSchedulePageResponseSchema
>;

export const SaleOrderScheduleResponseSchema = z.object({
  base_start_date: z.string(),
  business_unit_code: z.string(),
  cron_expression: z.string(),
  customer_code: z.string(),
  id: z.number(),
  item_source_type: z.string(),
  items: z.any(),
  last_error: z.string(),
  last_run_at: z.string(),
  last_run_status: z.string(),
  next_run_at: z.string(),
  order_date_offset_days: z.number(),
  recurrence_interval_weeks: z.number(),
  remark: z.string(),
  retry_count: z.number(),
  retry_limit: z.number(),
  status: z.string(),
  trigger_type: z.string(),
});
export type SaleOrderScheduleResponse = z.infer<
  typeof SaleOrderScheduleResponseSchema
>;

export const ToggleSaleOrderScheduleBodySchema = z.object({
  $schema: z.string().optional(),
  active: z.boolean(),
});
export type ToggleSaleOrderScheduleBody = z.infer<
  typeof ToggleSaleOrderScheduleBodySchema
>;

export const TriggerEventBodySchema = z.object({
  $schema: z.string().optional(),
  business_unit_code: z.string(),
  customer_code: z.string(),
  idempotency_key: z.string(),
  items: z.any(),
});
export type TriggerEventBody = z.infer<typeof TriggerEventBodySchema>;

// -- Request & Response Types --
export type SaleorderscheduleSaleorderscheduleTriggerPayload = TriggerEventBody;

export const SaleorderscheduleSaleorderscheduleTriggerResponseSchema = z.any();
export type SaleorderscheduleSaleorderscheduleTriggerResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleTriggerResponseSchema
>;

export type SaleorderscheduleSaleorderscheduleListParams = {
  page?: number;
  size?: number;
  search?: string;
};

export const SaleorderscheduleSaleorderscheduleListResponseSchema =
  SaleOrderSchedulePageResponseSchema;
export type SaleorderscheduleSaleorderscheduleListResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleListResponseSchema
>;

export type SaleorderscheduleSaleorderscheduleCreatePayload =
  CreateSaleOrderScheduleBody;

export const SaleorderscheduleSaleorderscheduleCreateResponseSchema =
  SaleOrderScheduleResponseSchema;
export type SaleorderscheduleSaleorderscheduleCreateResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleCreateResponseSchema
>;

export const SaleorderscheduleSaleorderscheduleDeleteResponseSchema = z.any();
export type SaleorderscheduleSaleorderscheduleDeleteResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleDeleteResponseSchema
>;

export const SaleorderscheduleSaleorderscheduleGetResponseSchema =
  SaleOrderScheduleResponseSchema;
export type SaleorderscheduleSaleorderscheduleGetResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleGetResponseSchema
>;

export type SaleorderscheduleSaleorderscheduleUpdatePayload =
  CreateSaleOrderScheduleBody;

export const SaleorderscheduleSaleorderscheduleUpdateResponseSchema =
  SaleOrderScheduleResponseSchema;
export type SaleorderscheduleSaleorderscheduleUpdateResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleUpdateResponseSchema
>;

export type SaleorderscheduleSaleorderscheduleLogsParams = {
  page?: number;
  size?: number;
};

export const SaleorderscheduleSaleorderscheduleLogsResponseSchema =
  SaleOrderScheduleExecutionLogPageResponseSchema;
export type SaleorderscheduleSaleorderscheduleLogsResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleLogsResponseSchema
>;

export const SaleorderscheduleSaleorderscheduleForcerunResponseSchema = z.any();
export type SaleorderscheduleSaleorderscheduleForcerunResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleForcerunResponseSchema
>;

export type SaleorderscheduleSaleorderscheduleTogglePayload =
  ToggleSaleOrderScheduleBody;

export const SaleorderscheduleSaleorderscheduleToggleResponseSchema =
  SaleOrderScheduleResponseSchema;
export type SaleorderscheduleSaleorderscheduleToggleResponse = z.infer<
  typeof SaleorderscheduleSaleorderscheduleToggleResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
