// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  CreateSaleOrderBody,
  SaleOrderResponse,
  SaleOrderSaleorderCreatePayload,
  SaleOrderSaleorderCreateResponse,
} from "./saleorder.types";
import { SaleOrderSaleorderCreateResponseSchema } from "./saleorder.types";

export type {
  CreateSaleOrderBody,
  SaleOrderResponse,
  SaleOrderSaleorderCreatePayload,
  SaleOrderSaleorderCreateResponse,
};

export class SaleOrderService extends BaseService<"saleorder"> {
  constructor(client: ApiClient) {
    super(client, "saleorder");
  }

  /**
   * saleorder-create
   * Create a sale order

   * @param payload - Request body (`SaleOrderSaleorderCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderSaleorderCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleorderCreate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderCreate(
    payload: SaleOrderSaleorderCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderSaleorderCreateResponse, AppApiErrorData>
  > {
    return this.client.post<SaleOrderSaleorderCreateResponse, AppApiErrorData>(
      `/api/v1/sales-orders`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: SaleOrderSaleorderCreateResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
