// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Shared Models --
export const SuccessResponseSchema = z.object({
  message: z.string().optional(),
});
export type SuccessResponse = z.infer<typeof SuccessResponseSchema>;

// -- Specific Models for saleorder --
export const BulkSendToWMSRequestBodySchema = z.object({
  ids: z.array(z.string()),
});
export type BulkSendToWMSRequestBody = z.infer<
  typeof BulkSendToWMSRequestBodySchema
>;

export const BulkSendToWMSResponseSchema = z.object({
  errors: z.record(z.string(), z.string()).optional(),
  success_ids: z.array(z.string()).optional(),
});
export type BulkSendToWMSResponse = z.infer<typeof BulkSendToWMSResponseSchema>;

export const SaleOrderItemResponseSchema = z.object({
  currency: z.string().optional(),
  item_code: z.string().optional(),
  quantity: z.number().optional(),
  sub_total: z.number().optional(),
  unit_price: z.number().optional(),
  uom: z.string().optional(),
});
export type SaleOrderItemResponse = z.infer<typeof SaleOrderItemResponseSchema>;

export const SaleOrderResponseSchema = z.object({
  business_unit_code: z.string().optional(),
  currency: z.string().optional(),
  customer_code: z.string().optional(),
  id: z.string().optional(),
  items: z.array(SaleOrderItemResponseSchema).optional(),
  order_date: z.string().optional(),
  order_no: z.string().optional(),
  order_type: z.string().optional(),
  remark: z.string().optional(),
  status: z.string().optional(),
  total_price: z.number().optional(),
  wms_file_name: z.string().optional(),
});
export type SaleOrderResponse = z.infer<typeof SaleOrderResponseSchema>;

export const SaleOrderPageResponseSchema = z.object({
  items: z.array(SaleOrderResponseSchema).optional(),
  page: z.number().optional(),
  size: z.number().optional(),
  total: z.number().optional(),
  total_pages: z.number().optional(),
});
export type SaleOrderPageResponse = z.infer<typeof SaleOrderPageResponseSchema>;

// -- Request & Response Types --

export const SaleOrderSaleOrderListResponseSchema = SaleOrderPageResponseSchema;
export type SaleOrderSaleOrderListResponse = z.infer<
  typeof SaleOrderSaleOrderListResponseSchema
>;

export type SaleOrderSaleOrderCreatePayload = any;

export const SaleOrderSaleOrderCreateResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderSaleOrderCreateResponse = z.infer<
  typeof SaleOrderSaleOrderCreateResponseSchema
>;

export type SaleOrderSaleOrderSendToWMSPayload = BulkSendToWMSRequestBody;

export const SaleOrderSaleOrderSendToWMSResponseSchema =
  BulkSendToWMSResponseSchema;
export type SaleOrderSaleOrderSendToWMSResponse = z.infer<
  typeof SaleOrderSaleOrderSendToWMSResponseSchema
>;

export const SaleOrderSaleOrderGetResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderSaleOrderGetResponse = z.infer<
  typeof SaleOrderSaleOrderGetResponseSchema
>;

export type SaleOrderSaleOrderUpdatePayload = any;

export const SaleOrderSaleOrderUpdateResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderSaleOrderUpdateResponse = z.infer<
  typeof SaleOrderSaleOrderUpdateResponseSchema
>;

export const SaleOrderSaleOrderDeleteResponseSchema = SuccessResponseSchema;
export type SaleOrderSaleOrderDeleteResponse = z.infer<
  typeof SaleOrderSaleOrderDeleteResponseSchema
>;

export const SaleOrderSaleOrderGetAuditLogsResponseSchema = z.record(
  z.string(),
  z.any(),
);
export type SaleOrderSaleOrderGetAuditLogsResponse = z.infer<
  typeof SaleOrderSaleOrderGetAuditLogsResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
