// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  EventItemDTO,
  SaleOrderScheduleExecutionLogDetailResponse,
  SaleOrderScheduleExecutionLogPageResponse,
  SaleOrderScheduleItemResponse,
  SaleOrderSchedulePageResponse,
  SaleOrderScheduleResponse,
  ToggleSaleOrderScheduleBody,
  TriggerEventBody,
  SaleOrderScheduleSaleOrderScheduleTriggerEventPayload,
  SaleOrderScheduleSaleOrderScheduleTriggerEventResponse,
  SaleOrderScheduleSaleOrderScheduleListResponse,
  SaleOrderScheduleSaleOrderScheduleCreatePayload,
  SaleOrderScheduleSaleOrderScheduleCreateResponse,
  SaleOrderScheduleSaleOrderScheduleGetResponse,
  SaleOrderScheduleSaleOrderScheduleUpdatePayload,
  SaleOrderScheduleSaleOrderScheduleUpdateResponse,
  SaleOrderScheduleSaleOrderScheduleDeleteResponse,
  SaleOrderScheduleSaleOrderScheduleListLogsResponse,
  SaleOrderScheduleSaleOrderScheduleForceRunResponse,
  SaleOrderScheduleSaleOrderScheduleTogglePayload,
  SaleOrderScheduleSaleOrderScheduleToggleResponse,
} from "./saleorderschedule.types";
import {
  SaleOrderScheduleSaleOrderScheduleTriggerEventResponseSchema,
  SaleOrderScheduleSaleOrderScheduleListResponseSchema,
  SaleOrderScheduleSaleOrderScheduleCreateResponseSchema,
  SaleOrderScheduleSaleOrderScheduleGetResponseSchema,
  SaleOrderScheduleSaleOrderScheduleUpdateResponseSchema,
  SaleOrderScheduleSaleOrderScheduleListLogsResponseSchema,
  SaleOrderScheduleSaleOrderScheduleForceRunResponseSchema,
  SaleOrderScheduleSaleOrderScheduleToggleResponseSchema,
} from "./saleorderschedule.types";

export type {
  EventItemDTO,
  SaleOrderScheduleExecutionLogDetailResponse,
  SaleOrderScheduleExecutionLogPageResponse,
  SaleOrderScheduleItemResponse,
  SaleOrderSchedulePageResponse,
  SaleOrderScheduleResponse,
  ToggleSaleOrderScheduleBody,
  TriggerEventBody,
  SaleOrderScheduleSaleOrderScheduleTriggerEventPayload,
  SaleOrderScheduleSaleOrderScheduleTriggerEventResponse,
  SaleOrderScheduleSaleOrderScheduleListResponse,
  SaleOrderScheduleSaleOrderScheduleCreatePayload,
  SaleOrderScheduleSaleOrderScheduleCreateResponse,
  SaleOrderScheduleSaleOrderScheduleGetResponse,
  SaleOrderScheduleSaleOrderScheduleUpdatePayload,
  SaleOrderScheduleSaleOrderScheduleUpdateResponse,
  SaleOrderScheduleSaleOrderScheduleDeleteResponse,
  SaleOrderScheduleSaleOrderScheduleListLogsResponse,
  SaleOrderScheduleSaleOrderScheduleForceRunResponse,
  SaleOrderScheduleSaleOrderScheduleTogglePayload,
  SaleOrderScheduleSaleOrderScheduleToggleResponse,
};

export class SaleOrderScheduleService extends BaseService<"saleorderschedule"> {
  constructor(client: ApiClient) {
    super(client, "saleorderschedule");
  }

  /**
   * saleOrderScheduleTriggerEvent
   * TriggerEvent
   * Requires permission: saleorderschedule:trigger

   * @param payload - Request body (`SaleOrderScheduleSaleOrderScheduleTriggerEventPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleTriggerEventResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleTriggerEvent(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleTriggerEvent(
    payload: SaleOrderScheduleSaleOrderScheduleTriggerEventPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<
      SaleOrderScheduleSaleOrderScheduleTriggerEventResponse,
      AppApiErrorData
    >
  > {
    return this.client.post<
      SaleOrderScheduleSaleOrderScheduleTriggerEventResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedule-triggers`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleTriggerEventResponseSchema,
    });
  }

  /**
   * saleOrderScheduleList
   * List
   * Requires permission: saleorderschedule:list
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleList(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleList(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderScheduleSaleOrderScheduleListResponse, AppApiErrorData>
  > {
    return this.client.get<
      SaleOrderScheduleSaleOrderScheduleListResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules`, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleListResponseSchema,
    });
  }

  /**
   * saleOrderScheduleCreate
   * Create
   * Requires permission: saleorderschedule:create

   * @param payload - Request body (`SaleOrderScheduleSaleOrderScheduleCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleCreate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleCreate(
    payload: SaleOrderScheduleSaleOrderScheduleCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderScheduleSaleOrderScheduleCreateResponse, AppApiErrorData>
  > {
    return this.client.post<
      SaleOrderScheduleSaleOrderScheduleCreateResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleCreateResponseSchema,
    });
  }

  /**
   * saleOrderScheduleGet
   * Get
   * Requires permission: saleorderschedule:get
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleGetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleGet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleGet(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderScheduleSaleOrderScheduleGetResponse, AppApiErrorData>
  > {
    return this.client.get<
      SaleOrderScheduleSaleOrderScheduleGetResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}`, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleGetResponseSchema,
    });
  }

  /**
   * saleOrderScheduleUpdate
   * Update
   * Requires permission: saleorderschedule:update
   * @param id - Path parameter

   * @param payload - Request body (`SaleOrderScheduleSaleOrderScheduleUpdatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleUpdateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleUpdate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleUpdate(
    id: string | number,
    payload: SaleOrderScheduleSaleOrderScheduleUpdatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderScheduleSaleOrderScheduleUpdateResponse, AppApiErrorData>
  > {
    return this.client.put<
      SaleOrderScheduleSaleOrderScheduleUpdateResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleUpdateResponseSchema,
    });
  }

  /**
   * saleOrderScheduleDelete
   * Delete
   * Requires permission: saleorderschedule:delete
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleDelete(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleDelete(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(
      `/api/v1/sale-orders/schedules/${id}`,
      {
        ...this.withSignal(config),
      },
    );
  }

  /**
   * saleOrderScheduleListLogs
   * ListLogs
   * Requires permission: saleorderschedule:logs
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleListLogsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleListLogs(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleListLogs(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<
      SaleOrderScheduleSaleOrderScheduleListLogsResponse,
      AppApiErrorData
    >
  > {
    return this.client.get<
      SaleOrderScheduleSaleOrderScheduleListLogsResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}/logs`, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleListLogsResponseSchema,
    });
  }

  /**
   * saleOrderScheduleForceRun
   * ForceRun
   * Requires permission: saleorderschedule:forcerun
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleForceRunResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleForceRun(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleForceRun(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<
      SaleOrderScheduleSaleOrderScheduleForceRunResponse,
      AppApiErrorData
    >
  > {
    return this.client.post<
      SaleOrderScheduleSaleOrderScheduleForceRunResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}/run-now`, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleForceRunResponseSchema,
    });
  }

  /**
   * saleOrderScheduleToggle
   * Toggle
   * Requires permission: saleorderschedule:toggle
   * @param id - Path parameter

   * @param payload - Request body (`SaleOrderScheduleSaleOrderScheduleTogglePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderScheduleSaleOrderScheduleToggleResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleOrderScheduleToggle(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderScheduleToggle(
    id: string | number,
    payload: SaleOrderScheduleSaleOrderScheduleTogglePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderScheduleSaleOrderScheduleToggleResponse, AppApiErrorData>
  > {
    return this.client.post<
      SaleOrderScheduleSaleOrderScheduleToggleResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}/toggle`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleOrderScheduleSaleOrderScheduleToggleResponseSchema,
    });
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
