// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Shared Models --
export const SuccessResponseSchema = z.object({
  message: z.string(),
});
export type SuccessResponse = z.infer<typeof SuccessResponseSchema>;

// -- Specific Models for saleorder --
export const BulkSendToWMSRequestBodySchema = z.object({
  $schema: z.string().optional(),
  ids: z.any(),
});
export type BulkSendToWMSRequestBody = z.infer<
  typeof BulkSendToWMSRequestBodySchema
>;

export const BulkSendToWMSResponseSchema = z.object({
  errors: z.record(z.string(), z.string()),
  success_ids: z.any(),
});
export type BulkSendToWMSResponse = z.infer<typeof BulkSendToWMSResponseSchema>;

export const CreateSaleOrderBodySchema = z.object({
  $schema: z.string().optional(),
  business_unit_code: z.string(),
  customer_code: z.string(),
  items: z.any(),
  order_date: z.string(),
  order_type: z.string(),
  remark: z.string(),
});
export type CreateSaleOrderBody = z.infer<typeof CreateSaleOrderBodySchema>;

export const SaleOrderPageResponseSchema = z.object({
  items: z.any(),
  page: z.number(),
  size: z.number(),
  total: z.number(),
  total_pages: z.number(),
});
export type SaleOrderPageResponse = z.infer<typeof SaleOrderPageResponseSchema>;

export const SaleOrderResponseSchema = z.object({
  business_unit_code: z.string(),
  currency: z.string(),
  customer_code: z.string(),
  id: z.number(),
  items: z.any(),
  order_date: z.string(),
  order_no: z.string(),
  order_type: z.string(),
  remark: z.string(),
  status: z.string(),
  total_price: z.number(),
  wms_file_name: z.string(),
});
export type SaleOrderResponse = z.infer<typeof SaleOrderResponseSchema>;

// -- Request & Response Types --

export type SaleOrderSaleorderListParams = {
  page?: number;
  size?: number;
  search?: string;
  sort_by?: string;
  sort_order?: string;
  business_unit_code?: string;
};

export const SaleOrderSaleorderListResponseSchema = SaleOrderPageResponseSchema;
export type SaleOrderSaleorderListResponse = z.infer<
  typeof SaleOrderSaleorderListResponseSchema
>;

export type SaleOrderSaleorderCreatePayload = CreateSaleOrderBody;

export const SaleOrderSaleorderCreateResponseSchema = SaleOrderResponseSchema;
export type SaleOrderSaleorderCreateResponse = z.infer<
  typeof SaleOrderSaleorderCreateResponseSchema
>;

export type SaleOrderSaleorderWmsPayload = BulkSendToWMSRequestBody;

export const SaleOrderSaleorderWmsResponseSchema = BulkSendToWMSResponseSchema;
export type SaleOrderSaleorderWmsResponse = z.infer<
  typeof SaleOrderSaleorderWmsResponseSchema
>;

export const SaleOrderSaleorderDeleteResponseSchema = SuccessResponseSchema;
export type SaleOrderSaleorderDeleteResponse = z.infer<
  typeof SaleOrderSaleorderDeleteResponseSchema
>;

export const SaleOrderSaleorderGetResponseSchema = SaleOrderResponseSchema;
export type SaleOrderSaleorderGetResponse = z.infer<
  typeof SaleOrderSaleorderGetResponseSchema
>;

export type SaleOrderSaleorderUpdatePayload = CreateSaleOrderBody;

export const SaleOrderSaleorderUpdateResponseSchema = SaleOrderResponseSchema;
export type SaleOrderSaleorderUpdateResponse = z.infer<
  typeof SaleOrderSaleorderUpdateResponseSchema
>;

export const SaleOrderSaleorderAuditlogsResponseSchema = z.any();
export type SaleOrderSaleorderAuditlogsResponse = z.infer<
  typeof SaleOrderSaleorderAuditlogsResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
