// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  CreateSaleOrderScheduleBody,
  SaleOrderScheduleExecutionLogPageResponse,
  SaleOrderSchedulePageResponse,
  SaleOrderScheduleResponse,
  ToggleSaleOrderScheduleBody,
  TriggerEventBody,
  SaleorderscheduleSaleorderscheduleTriggerPayload,
  SaleorderscheduleSaleorderscheduleTriggerResponse,
  SaleorderscheduleSaleorderscheduleListParams,
  SaleorderscheduleSaleorderscheduleListResponse,
  SaleorderscheduleSaleorderscheduleCreatePayload,
  SaleorderscheduleSaleorderscheduleCreateResponse,
  SaleorderscheduleSaleorderscheduleDeleteResponse,
  SaleorderscheduleSaleorderscheduleGetResponse,
  SaleorderscheduleSaleorderscheduleUpdatePayload,
  SaleorderscheduleSaleorderscheduleUpdateResponse,
  SaleorderscheduleSaleorderscheduleLogsParams,
  SaleorderscheduleSaleorderscheduleLogsResponse,
  SaleorderscheduleSaleorderscheduleForcerunResponse,
  SaleorderscheduleSaleorderscheduleTogglePayload,
  SaleorderscheduleSaleorderscheduleToggleResponse,
} from "./saleorderschedule.types";
import {
  SaleorderscheduleSaleorderscheduleTriggerResponseSchema,
  SaleorderscheduleSaleorderscheduleListResponseSchema,
  SaleorderscheduleSaleorderscheduleCreateResponseSchema,
  SaleorderscheduleSaleorderscheduleGetResponseSchema,
  SaleorderscheduleSaleorderscheduleUpdateResponseSchema,
  SaleorderscheduleSaleorderscheduleLogsResponseSchema,
  SaleorderscheduleSaleorderscheduleForcerunResponseSchema,
  SaleorderscheduleSaleorderscheduleToggleResponseSchema,
} from "./saleorderschedule.types";

export type {
  CreateSaleOrderScheduleBody,
  SaleOrderScheduleExecutionLogPageResponse,
  SaleOrderSchedulePageResponse,
  SaleOrderScheduleResponse,
  ToggleSaleOrderScheduleBody,
  TriggerEventBody,
  SaleorderscheduleSaleorderscheduleTriggerPayload,
  SaleorderscheduleSaleorderscheduleTriggerResponse,
  SaleorderscheduleSaleorderscheduleListParams,
  SaleorderscheduleSaleorderscheduleListResponse,
  SaleorderscheduleSaleorderscheduleCreatePayload,
  SaleorderscheduleSaleorderscheduleCreateResponse,
  SaleorderscheduleSaleorderscheduleDeleteResponse,
  SaleorderscheduleSaleorderscheduleGetResponse,
  SaleorderscheduleSaleorderscheduleUpdatePayload,
  SaleorderscheduleSaleorderscheduleUpdateResponse,
  SaleorderscheduleSaleorderscheduleLogsParams,
  SaleorderscheduleSaleorderscheduleLogsResponse,
  SaleorderscheduleSaleorderscheduleForcerunResponse,
  SaleorderscheduleSaleorderscheduleTogglePayload,
  SaleorderscheduleSaleorderscheduleToggleResponse,
};

export class SaleorderscheduleService extends BaseService<"saleorderschedule"> {
  constructor(client: ApiClient) {
    super(client, "saleorderschedule");
  }

  /**
   * saleorderschedule-trigger
   * Inbound Event Trigger for matching schedules

   * @param payload - Request body (`SaleorderscheduleSaleorderscheduleTriggerPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleTriggerResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleTrigger(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleTrigger(
    payload: SaleorderscheduleSaleorderscheduleTriggerPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<
      SaleorderscheduleSaleorderscheduleTriggerResponse,
      AppApiErrorData
    >
  > {
    return this.client.post<
      SaleorderscheduleSaleorderscheduleTriggerResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedule-triggers`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleorderscheduleSaleorderscheduleTriggerResponseSchema,
    });
  }

  /**
   * saleorderschedule-list
   * List Sale Order Schedules
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleList(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleList(
    params?: SaleorderscheduleSaleorderscheduleListParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<
    ApiResult<SaleorderscheduleSaleorderscheduleListResponse, AppApiErrorData>
  > {
    return this.client.get<
      SaleorderscheduleSaleorderscheduleListResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules`, {
      ...this.withSignal(config),
      params,
      zodSchema: SaleorderscheduleSaleorderscheduleListResponseSchema,
    });
  }

  /**
   * saleorderschedule-create
   * Create Sale Order Schedule

   * @param payload - Request body (`SaleorderscheduleSaleorderscheduleCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleCreate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleCreate(
    payload: SaleorderscheduleSaleorderscheduleCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleorderscheduleSaleorderscheduleCreateResponse, AppApiErrorData>
  > {
    return this.client.post<
      SaleorderscheduleSaleorderscheduleCreateResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleorderscheduleSaleorderscheduleCreateResponseSchema,
    });
  }

  /**
   * saleorderschedule-delete
   * Delete Sale Order Schedule
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleDelete(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleDelete(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(
      `/api/v1/sale-orders/schedules/${id}`,
      {
        ...this.withSignal(config),
      },
    );
  }

  /**
   * saleorderschedule-get
   * Get Sale Order Schedule Details
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleGetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleGet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleGet(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleorderscheduleSaleorderscheduleGetResponse, AppApiErrorData>
  > {
    return this.client.get<
      SaleorderscheduleSaleorderscheduleGetResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}`, {
      ...this.withSignal(config),
      zodSchema: SaleorderscheduleSaleorderscheduleGetResponseSchema,
    });
  }

  /**
   * saleorderschedule-update
   * Update Sale Order Schedule
   * @param id - Path parameter

   * @param payload - Request body (`SaleorderscheduleSaleorderscheduleUpdatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleUpdateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleUpdate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleUpdate(
    id: string | number,
    payload: SaleorderscheduleSaleorderscheduleUpdatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleorderscheduleSaleorderscheduleUpdateResponse, AppApiErrorData>
  > {
    return this.client.put<
      SaleorderscheduleSaleorderscheduleUpdateResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleorderscheduleSaleorderscheduleUpdateResponseSchema,
    });
  }

  /**
   * saleorderschedule-logs
   * Get Sale Order Schedule execution logs
   * @param id - Path parameter
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleLogsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleLogs(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleLogs(
    id: string | number,
    params?: SaleorderscheduleSaleorderscheduleLogsParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<
    ApiResult<SaleorderscheduleSaleorderscheduleLogsResponse, AppApiErrorData>
  > {
    return this.client.get<
      SaleorderscheduleSaleorderscheduleLogsResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}/logs`, {
      ...this.withSignal(config),
      params,
      zodSchema: SaleorderscheduleSaleorderscheduleLogsResponseSchema,
    });
  }

  /**
   * saleorderschedule-forcerun
   * Force execution of Sale Order Schedule now
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleForcerunResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleForcerun(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleForcerun(
    id: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<
      SaleorderscheduleSaleorderscheduleForcerunResponse,
      AppApiErrorData
    >
  > {
    return this.client.post<
      SaleorderscheduleSaleorderscheduleForcerunResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}/run-now`, {
      ...this.withSignal(config),
      zodSchema: SaleorderscheduleSaleorderscheduleForcerunResponseSchema,
    });
  }

  /**
   * saleorderschedule-toggle
   * Toggle Sale Order Schedule Active/Inactive status
   * @param id - Path parameter

   * @param payload - Request body (`SaleorderscheduleSaleorderscheduleTogglePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleorderscheduleSaleorderscheduleToggleResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorderschedule.saleorderscheduleToggle(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleorderscheduleToggle(
    id: string | number,
    payload: SaleorderscheduleSaleorderscheduleTogglePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleorderscheduleSaleorderscheduleToggleResponse, AppApiErrorData>
  > {
    return this.client.post<
      SaleorderscheduleSaleorderscheduleToggleResponse,
      AppApiErrorData
    >(`/api/v1/sale-orders/schedules/${id}/toggle`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleorderscheduleSaleorderscheduleToggleResponseSchema,
    });
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
