// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  AuditLogResponse,
  BulkSendToWMSRequestBody,
  BulkSendToWMSResponse,
  SaleOrderItemResponse,
  SaleOrderPageResponse,
  SaleOrderResponse,
  SaleOrderSaleOrderListResponse,
  SaleOrderSaleOrderCreatePayload,
  SaleOrderSaleOrderCreateResponse,
  SaleOrderSaleOrderSendToWMSPayload,
  SaleOrderSaleOrderSendToWMSResponse,
  SaleOrderSaleOrderDeleteResponse,
  SaleOrderSaleOrderGetResponse,
  SaleOrderSaleOrderUpdatePayload,
  SaleOrderSaleOrderUpdateResponse,
  SaleOrderSaleOrderGetAuditLogsResponse,
} from "./saleorder.types";
import {
  SaleOrderSaleOrderListResponseSchema,
  SaleOrderSaleOrderCreateResponseSchema,
  SaleOrderSaleOrderSendToWMSResponseSchema,
  SaleOrderSaleOrderGetResponseSchema,
  SaleOrderSaleOrderUpdateResponseSchema,
  SaleOrderSaleOrderGetAuditLogsResponseSchema,
} from "./saleorder.types";

export type {
  AuditLogResponse,
  BulkSendToWMSRequestBody,
  BulkSendToWMSResponse,
  SaleOrderItemResponse,
  SaleOrderPageResponse,
  SaleOrderResponse,
  SaleOrderSaleOrderListResponse,
  SaleOrderSaleOrderCreatePayload,
  SaleOrderSaleOrderCreateResponse,
  SaleOrderSaleOrderSendToWMSPayload,
  SaleOrderSaleOrderSendToWMSResponse,
  SaleOrderSaleOrderDeleteResponse,
  SaleOrderSaleOrderGetResponse,
  SaleOrderSaleOrderUpdatePayload,
  SaleOrderSaleOrderUpdateResponse,
  SaleOrderSaleOrderGetAuditLogsResponse,
};

export class SaleOrderService extends BaseService<"saleorder"> {
  constructor(client: ApiClient) {
    super(client, "saleorder");
  }

  /**
   * saleOrderList
   * List
   * Requires permission: saleorder:list
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderSaleOrderListResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleOrderList(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderList(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderSaleOrderListResponse, AppApiErrorData>
  > {
    return this.client.get<SaleOrderSaleOrderListResponse, AppApiErrorData>(
      `/api/v1/sales-orders`,
      {
        ...this.withSignal(config),
        zodSchema: SaleOrderSaleOrderListResponseSchema,
      },
    );
  }

  /**
   * saleOrderCreate
   * Create เป็นการสร้างใบสั่งซื้อใหม่
   * Requires permission: saleorder:create

   * @param payload - Request body (`SaleOrderSaleOrderCreatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderSaleOrderCreateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleOrderCreate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderCreate(
    payload: SaleOrderSaleOrderCreatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderSaleOrderCreateResponse, AppApiErrorData>
  > {
    return this.client.post<SaleOrderSaleOrderCreateResponse, AppApiErrorData>(
      `/api/v1/sales-orders`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: SaleOrderSaleOrderCreateResponseSchema,
      },
    );
  }

  /**
   * saleOrderSendToWMS
   * SendToWMS
   * Requires permission: saleorder:wms

   * @param payload - Request body (`SaleOrderSaleOrderSendToWMSPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderSaleOrderSendToWMSResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleOrderSendToWMS(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderSendToWMS(
    payload: SaleOrderSaleOrderSendToWMSPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderSaleOrderSendToWMSResponse, AppApiErrorData>
  > {
    return this.client.post<
      SaleOrderSaleOrderSendToWMSResponse,
      AppApiErrorData
    >(`/api/v1/sales-orders/wms`, payload, {
      ...this.withSignal(config),
      zodSchema: SaleOrderSaleOrderSendToWMSResponseSchema,
    });
  }

  /**
   * saleOrderDelete
   * Delete
   * Requires permission: saleorder:delete
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleOrderDelete(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderDelete(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/api/v1/sales-orders/${id}`, {
      ...this.withSignal(config),
    });
  }

  /**
   * saleOrderGet
   * Get
   * Requires permission: saleorder:get
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderSaleOrderGetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleOrderGet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderGet(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderSaleOrderGetResponse, AppApiErrorData>
  > {
    return this.client.get<SaleOrderSaleOrderGetResponse, AppApiErrorData>(
      `/api/v1/sales-orders/${id}`,
      {
        ...this.withSignal(config),
        zodSchema: SaleOrderSaleOrderGetResponseSchema,
      },
    );
  }

  /**
   * saleOrderUpdate
   * Update
   * Requires permission: saleorder:update
   * @param id - Path parameter

   * @param payload - Request body (`SaleOrderSaleOrderUpdatePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderSaleOrderUpdateResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleOrderUpdate(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderUpdate(
    id: string,
    payload: SaleOrderSaleOrderUpdatePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderSaleOrderUpdateResponse, AppApiErrorData>
  > {
    return this.client.put<SaleOrderSaleOrderUpdateResponse, AppApiErrorData>(
      `/api/v1/sales-orders/${id}`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: SaleOrderSaleOrderUpdateResponseSchema,
      },
    );
  }

  /**
   * saleOrderGetAuditLogs
   * GetAuditLogs
   * Requires permission: saleorder:auditlogs
   * @param id - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `SaleOrderSaleOrderGetAuditLogsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.saleorder.saleOrderGetAuditLogs(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public saleOrderGetAuditLogs(
    id: string,
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<SaleOrderSaleOrderGetAuditLogsResponse, AppApiErrorData>
  > {
    return this.client.get<
      SaleOrderSaleOrderGetAuditLogsResponse,
      AppApiErrorData
    >(`/api/v1/sales-orders/${id}/audit-logs`, {
      ...this.withSignal(config),
      zodSchema: SaleOrderSaleOrderGetAuditLogsResponseSchema,
    });
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
