// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type { TestErrorResponse, TestPanicResponse } from "./test.types";
import { TestErrorResponseSchema, TestPanicResponseSchema } from "./test.types";

export type { TestErrorResponse, TestPanicResponse };

export class TestService extends BaseService<"test"> {
  constructor(client: ApiClient) {
    super(client, "test");
  }

  /**
   * test:error
   * Test Error Logging
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `TestErrorResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.test.error(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public error(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<TestErrorResponse, AppApiErrorData>> {
    return this.client.get<TestErrorResponse, AppApiErrorData>(
      `/api/v1/test/error`,
      {
        ...this.withSignal(config),
        zodSchema: TestErrorResponseSchema,
      },
    );
  }

  /**
   * test:panic
   * Test Panic Recovery
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `TestPanicResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.test.panic(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public panic(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<TestPanicResponse, AppApiErrorData>> {
    return this.client.get<TestPanicResponse, AppApiErrorData>(
      `/api/v1/test/panic`,
      {
        ...this.withSignal(config),
        zodSchema: TestPanicResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
