// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Request & Response Types --

export const TestErrorResponseSchema = z.string();
export type TestErrorResponse = z.infer<typeof TestErrorResponseSchema>;

export const TestPanicResponseSchema = z.string();
export type TestPanicResponse = z.infer<typeof TestPanicResponseSchema>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
