// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Request & Response Types --

export const TestTestTriggerErrorResponseSchema = z.record(z.string(), z.any());
export type TestTestTriggerErrorResponse = z.infer<
  typeof TestTestTriggerErrorResponseSchema
>;

export const TestTestTriggerPanicResponseSchema = z.record(z.string(), z.any());
export type TestTestTriggerPanicResponse = z.infer<
  typeof TestTestTriggerPanicResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
