// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  TestTestTriggerErrorResponse,
  TestTestTriggerPanicResponse,
} from "./test.types";
import {
  TestTestTriggerErrorResponseSchema,
  TestTestTriggerPanicResponseSchema,
} from "./test.types";

export type { TestTestTriggerErrorResponse, TestTestTriggerPanicResponse };

export class TestService extends BaseService<"test"> {
  constructor(client: ApiClient) {
    super(client, "test");
  }

  /**
   * testTriggerError
   * TriggerError
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `TestTestTriggerErrorResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.test.testTriggerError(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public testTriggerError(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<TestTestTriggerErrorResponse, AppApiErrorData>
  > {
    return this.client.get<TestTestTriggerErrorResponse, AppApiErrorData>(
      `/api/v1/test/error`,
      {
        ...this.withSignal(config),
        zodSchema: TestTestTriggerErrorResponseSchema,
      },
    );
  }

  /**
   * testTriggerPanic
   * TriggerPanic
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `TestTestTriggerPanicResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.test.testTriggerPanic(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public testTriggerPanic(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<TestTestTriggerPanicResponse, AppApiErrorData>
  > {
    return this.client.get<TestTestTriggerPanicResponse, AppApiErrorData>(
      `/api/v1/test/panic`,
      {
        ...this.withSignal(config),
        zodSchema: TestTestTriggerPanicResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
