// AUTO-GENERATED BY specshot (custom template — Singleton Pattern) - DO NOT DELETE MAGIC COMMENTS
// Design Pattern: Singleton — single shared service instance with centralized config.
// Use case: Single API client shared across the entire app (e.g. global state, shared cache).

import type { Pet, CreatePetRequest, PetsListPetsResponse, PetsCreatePetPayload, PetsCreatePetResponse, PetsGetPetResponse } from "./pets.types";
export type { Pet, CreatePetRequest, PetsListPetsResponse, PetsCreatePetPayload, PetsCreatePetResponse, PetsGetPetResponse } from "./pets.types";

import { ApiError } from "./models";

// ─────────────────────────────────────────────
// Singleton Service
// ─────────────────────────────────────────────

export class PetsService {
  private static _instance: PetsService | null = null;
  private _baseUrl: string = "";
  private _defaultHeaders: Record<string, string> = {};
  private _cache: Map<string, { data: unknown; expiry: number }> = new Map();
  private _cacheTTL: number = 60000; // 60s

  private constructor() {}

  /** Get the singleton instance. */
  static getInstance(): PetsService {
    if (!PetsService._instance) {
      PetsService._instance = new PetsService();
    }
    return PetsService._instance;
  }

  /** Set the API base URL. */
  setBaseUrl(url: string): void {
    this._baseUrl = url.replace(/\/+$/, "");
  }

  /** Set default headers (e.g. Authorization). */
  setDefaultHeaders(headers: Record<string, string>): void {
    this._defaultHeaders = { ...this._defaultHeaders, ...headers };
  }

  /** Set cache TTL in milliseconds (0 = disabled). */
  setCacheTTL(ttl: number): void {
    this._cacheTTL = ttl;
  }

  private _getCached<T>(key: string): T | null {
    if (this._cacheTTL === 0) return null;
    const hit = this._cache.get(key);
    if (hit && hit.expiry > Date.now()) return hit.data as T;
    if (hit) this._cache.delete(key);
    return null;
  }

  private _setCached(key: string, data: unknown): void {
    if (this._cacheTTL === 0) return;
    this._cache.set(key, { data, expiry: Date.now() + this._cacheTTL });
  }

  private async _request<T>(
    method: string,
    url: string,
    body?: unknown,
    init?: RequestInit,
  ): Promise<T> {
    const _res = await fetch(url, {
      method,
      headers: {
        "Content-Type": "application/json",
        ...this._defaultHeaders,
        ...init?.headers,
      },
      ...(body ? { body: JSON.stringify(body) } : {}),
      ...init,
    });
    if (!_res.ok) {
      const _errBody = await _res.text().catch(() => "");
      throw new ApiError(`${method} ${url} failed: ${_res.status}`, _res.status, _errBody);
    }
    return _res.json() as Promise<T>;
  }

  /**
   * listPets
   * List all pets
   * @throws {ApiError} On non-2xx response
   */
  async listPets(
    init?: RequestInit
  ): Promise<PetsListPetsResponse> {
    let _url = `${this._baseUrl}/pets`;
    const _cacheKey = `${_url}`;
    const _cached = this._getCached<PetsListPetsResponse>(_cacheKey);
    if (_cached) return _cached;
    const _data = await this._request<PetsListPetsResponse>("get", _url, init);
    this._setCached(_cacheKey, _data);
    return _data;
  }

  /**
   * createPet
   * Create a pet
   * @throws {ApiError} On non-2xx response
   */
  async createPet(
    body: PetsCreatePetPayload,
    init?: RequestInit
  ): Promise<PetsCreatePetResponse> {
    let _url = `${this._baseUrl}/pets`;
    const _cacheKey = `${_url}`;
    const _cached = this._getCached<PetsCreatePetResponse>(_cacheKey);
    if (_cached) return _cached;
    const _data = await this._request<PetsCreatePetResponse>("post", _url, body, init);
    this._setCached(_cacheKey, _data);
    return _data;
  }

  /**
   * getPet
   * Get a pet by ID
   * @throws {ApiError} On non-2xx response
   */
  async getPet(
    petId: string | number,
    init?: RequestInit
  ): Promise<PetsGetPetResponse> {
    let _url = `${this._baseUrl}/pets/${petId}`;
    const _cacheKey = `${_url}`;
    const _cached = this._getCached<PetsGetPetResponse>(_cacheKey);
    if (_cached) return _cached;
    const _data = await this._request<PetsGetPetResponse>("get", _url, init);
    this._setCached(_cacheKey, _data);
    return _data;
  }

}

// Convenience: pre-exported singleton
export const petsService = PetsService.getInstance();

// --- CUSTOM CODE START ---
// Add your custom code here. Do not remove these comments.
// --- CUSTOM CODE END ---
