// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  LeaderboardEntry,
  LeaderboardGetLeaderboardResponse,
} from "./leaderboard.types";

export type { LeaderboardEntry, LeaderboardGetLeaderboardResponse };

export class LeaderboardService extends BaseService<"leaderboard"> {
  constructor(client: ApiClient) {
    super(client, "leaderboard");
  }

  /**
   * getLeaderboard
   * Get top players by score
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `LeaderboardGetLeaderboardResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.leaderboard.getLeaderboard(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getLeaderboard(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<LeaderboardGetLeaderboardResponse, AppApiErrorData>
  > {
    return this.client.get<LeaderboardGetLeaderboardResponse, AppApiErrorData>(
      `/leaderboard`,
      {
        ...this.withSignal(config),
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
