// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for leaderboard --
export const LeaderboardEntrySchema = z.object({
  rank: z.number(),
  username: z.string(),
  score: z.number(),
  totalVotes: z.number().optional(),
  accuracy: z.number().optional(),
});
export type LeaderboardEntry = z.infer<typeof LeaderboardEntrySchema>;

// -- Request & Response Types --

export const LeaderboardGetLeaderboardResponseSchema = z.array(
  LeaderboardEntrySchema,
);
export type LeaderboardGetLeaderboardResponse = z.infer<
  typeof LeaderboardGetLeaderboardResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
