// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  Meme,
  CreateMemeRequest,
  VoteRequest,
  VoteResult,
  MemesListMemesParams,
  MemesListMemesResponse,
  MemesCreateMemePayload,
  MemesCreateMemeResponse,
  MemesGetMemeResponse,
  MemesVoteMemePayload,
  MemesVoteMemeResponse,
} from "./memes.types";

export type {
  Meme,
  CreateMemeRequest,
  VoteRequest,
  VoteResult,
  MemesListMemesParams,
  MemesListMemesResponse,
  MemesCreateMemePayload,
  MemesCreateMemeResponse,
  MemesGetMemeResponse,
  MemesVoteMemePayload,
  MemesVoteMemeResponse,
};

export class MemesService extends BaseService<"memes"> {
  constructor(client: ApiClient) {
    super(client, "memes");
  }

  /**
   * listMemes
   * List memes to vote on
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MemesListMemesResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.memes.listMemes(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listMemes(
    config?: Omit<AppRequestConfig, "params"> & {
      params?: MemesListMemesParams;
    },
  ): CancelablePromise<ApiResult<MemesListMemesResponse, AppApiErrorData>> {
    return this.client.get<MemesListMemesResponse, AppApiErrorData>(`/memes`, {
      ...this.withSignal(config),
    });
  }

  /**
   * createMeme
   * Submit a new meme for voting

   * @param payload - Request body (`MemesCreateMemePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MemesCreateMemeResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.memes.createMeme(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createMeme(
    payload: MemesCreateMemePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<MemesCreateMemeResponse, AppApiErrorData>> {
    return this.client.post<MemesCreateMemeResponse, AppApiErrorData>(
      `/memes`,
      payload,
      {
        ...this.withSignal(config),
      },
    );
  }

  /**
   * getMeme
   * Get a single meme by ID
   * @param memeId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MemesGetMemeResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.memes.getMeme(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getMeme(
    memeId: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<MemesGetMemeResponse, AppApiErrorData>> {
    return this.client.get<MemesGetMemeResponse, AppApiErrorData>(
      `/memes/${memeId}`,
      {
        ...this.withSignal(config),
      },
    );
  }

  /**
   * voteMeme
   * Vote whether a meme is real or fake
   * @param memeId - Path parameter

   * @param payload - Request body (`MemesVoteMemePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `MemesVoteMemeResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.memes.voteMeme(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public voteMeme(
    memeId: string | number,
    payload: MemesVoteMemePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<MemesVoteMemeResponse, AppApiErrorData>> {
    return this.client.post<MemesVoteMemeResponse, AppApiErrorData>(
      `/memes/${memeId}/vote`,
      payload,
      {
        ...this.withSignal(config),
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
