// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for memes --
export const MemeSchema = z.object({
  id: z.string(),
  imageUrl: z.string(),
  caption: z.string().optional(),
  category: z.enum(["news", "history", "science", "pop-culture"]).optional(),
  isReal: z.boolean(),
  totalVotes: z.number().optional(),
  realVotes: z.number().optional(),
  fakeVotes: z.number().optional(),
});
export type Meme = z.infer<typeof MemeSchema>;

export const CreateMemeRequestSchema = z.object({
  imageUrl: z.string(),
  caption: z.string().optional(),
  category: z.enum(["news", "history", "science", "pop-culture"]).optional(),
  isReal: z.boolean(),
});
export type CreateMemeRequest = z.infer<typeof CreateMemeRequestSchema>;

export const VoteRequestSchema = z.object({
  guess: z.enum(["real", "fake"]),
});
export type VoteRequest = z.infer<typeof VoteRequestSchema>;

export const VoteResultSchema = z.object({
  correct: z.boolean(),
  isReal: z.boolean(),
  score: z.number().optional(),
  totalVotes: z.number().optional(),
  realVotes: z.number().optional(),
  fakeVotes: z.number().optional(),
});
export type VoteResult = z.infer<typeof VoteResultSchema>;

// -- Request & Response Types --

export type MemesListMemesParams = {
  limit?: number;
  category?: "news" | "history" | "science" | "pop-culture";
};

export type MemesListMemesResponse = Meme[];

export type MemesCreateMemePayload = CreateMemeRequest;

export type MemesCreateMemeResponse = void;

export type MemesGetMemeResponse = Meme;

export type MemesVoteMemePayload = VoteRequest;

export type MemesVoteMemeResponse = VoteResult;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
