// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { z } from "zod";

export const Pet = z.object({
  id: z.string(),
  name: z.string(),
  age: z.number().optional(),
  tag: z.string().optional(),
});
export type Pet = z.infer<typeof Pet>;


// --- CUSTOM CODE START ---
// Add your custom Zod models here. Do not remove these comments.
// --- CUSTOM CODE END ---
