// AUTO-GENERATED BY specshot
import { z } from "zod";

import { Pet, PetSchema } from "./models";

// -- Specific Models for stores --
export const StoreSchema = z.object({
  id: z.string(),
  address: z.string(),
  pet: PetSchema.optional(),
});
export type Store = z.infer<typeof StoreSchema>;


// -- Request & Response Types --


export type StoresListStoresResponse = Store[];


// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
