// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type { Store, StoresListStoresResponse } from "./stores.types";

export type { Store, StoresListStoresResponse };

export class StoresService extends BaseService<"stores"> {
  constructor(client: ApiClient) {
    super(client, "stores");
  }

  /**
   * listStores
   * List stores
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoresListStoresResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.stores.listStores(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listStores(
    config?: AppRequestConfig
  ): Promise<ApiResult<StoresListStoresResponse, AppApiErrorData>> {
    return this.client.get<StoresListStoresResponse, AppApiErrorData>(
      `/stores`,
      this.withSignal(config)
    );
  }


  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  // --- CUSTOM CODE END ---
}
