import { useState } from "react";
import { browserClient, browserApi, useApi, Meme } from "./api/meme";

const ENDPOINTS = {
  real: "http://localhost:3000",
  fake: "http://localhost:3457",
};

// Set initial base URL
browserClient.options.baseUrl = ENDPOINTS.real;

export default function App() {
  const [apiUrl, setApiUrl] = useState(ENDPOINTS.real);

  // Use the SWR hook generated by Specshot!
  // The proxy exposes the method name directly (e.g. listMemes)
  const { data: memes, error, isLoading, mutate } = useApi.memes.listMemes();

  const toggleEndpoint = (mode: "real" | "fake") => {
    const newUrl = mode === "real" ? ENDPOINTS.real : ENDPOINTS.fake;
    setApiUrl(newUrl);
    browserClient.options.baseUrl = newUrl;
    // Re-fetch data on endpoint change
    mutate();
  };

  const isReal = apiUrl === ENDPOINTS.real;

  return (
    <div className="app">
      <div className="endpoint-toggle">
        <button
          className={`ep-btn ${isReal ? "active" : ""}`}
          onClick={() => toggleEndpoint("real")}
        >
          Real API (3000)
        </button>
        <button
          className={`ep-btn ${!isReal ? "active" : ""}`}
          onClick={() => toggleEndpoint("fake")}
        >
          Fake API (3457)
        </button>
      </div>

      <div className="api-bar">
        Connected to: <span className={isReal ? "real" : "fake"}>{apiUrl}</span>
      </div>

      {isLoading && <p className="status">Loading...</p>}
      {error && <p className="status error">{error.message || "An error occurred"}</p>}

      <div className="meme-list">
        {memes?.map((meme) => (
          <MemeCard key={meme.id} meme={meme} />
        ))}
      </div>
    </div>
  );
}

function MemeCard({ meme }: { meme: Meme }) {
  const [voted, setVoted] = useState<any>(null);
  const [isMutating, setIsMutating] = useState(false);

  const handleVote = async (guess: "real" | "fake") => {
    if (voted) return;
    setIsMutating(true);
    try {
      // Use the direct API client for POST requests
      const res = await browserApi.memes.voteMeme(meme.id, { guess });
      if (res.ok) {
        setVoted(res.data);
      }
    } catch {
      // ignore
    } finally {
      setIsMutating(false);
    }
  };

  return (
    <div className="card">
      <img src={meme.imageUrl} alt={meme.caption} />
      <p className="caption">{meme.caption}</p>
      <span className="category">{meme.category}</span>

      {!voted ? (
        <div className="actions">
          <button className="btn btn-real" onClick={() => handleVote("real")} disabled={isMutating}>
            Real
          </button>
          <button className="btn btn-fake" onClick={() => handleVote("fake")} disabled={isMutating}>
            Fake
          </button>
        </div>
      ) : (
        <div className="result">
          <span className={voted.correct ? "green" : "red"}>
            {voted.correct ? "Correct" : "Wrong"} — it's {voted.isReal ? "REAL" : "FAKE"}
          </span>
          <span className="vote-stats">
            R: {voted.realVotes} / F: {voted.fakeVotes}
          </span>
        </div>
      )}
    </div>
  );
}
