// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  Meme,
  CreateMemeRequest,
  VoteRequest,
  VoteResult,
  memesListMemesParams,
  memesListMemesResponse,
  memesCreateMemePayload,
  memesCreateMemeResponse,
  memesGetMemeResponse,
  memesVoteMemePayload,
  memesVoteMemeResponse,
} from "./memes.types";

export type {
  Meme,
  CreateMemeRequest,
  VoteRequest,
  VoteResult,
  memesListMemesParams,
  memesListMemesResponse,
  memesCreateMemePayload,
  memesCreateMemeResponse,
  memesGetMemeResponse,
  memesVoteMemePayload,
  memesVoteMemeResponse,
};

export class memesService extends BaseService<"memes"> {
  constructor(client: ApiClient) {
    super(client, "memes");
  }

  /**
   * listMemes
   * List memes to vote on
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `memesListMemesResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.memes.listMemes(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listMemes(
    config?: Omit<AppRequestConfig, "params"> & {
      params?: memesListMemesParams;
    },
  ): Promise<ApiResult<memesListMemesResponse, AppApiErrorData>> {
    return this.client.get<memesListMemesResponse, AppApiErrorData>(
      `/memes`,
      this.withSignal(config),
    );
  }

  /**
   * createMeme
   * Submit a new meme for voting

   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `memesCreateMemeResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.memes.createMeme(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createMeme(
    payload: memesCreateMemePayload,
    config?: AppRequestConfig,
  ): Promise<ApiResult<memesCreateMemeResponse, AppApiErrorData>> {
    return this.client.post<memesCreateMemeResponse, AppApiErrorData>(
      `/memes`,
      payload,
      this.withSignal(config),
    );
  }

  /**
   * getMeme
   * Get a single meme by ID
   * @param memeId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `memesGetMemeResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.memes.getMeme(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getMeme(
    memeId: string | number,
    config?: AppRequestConfig,
  ): Promise<ApiResult<memesGetMemeResponse, AppApiErrorData>> {
    return this.client.get<memesGetMemeResponse, AppApiErrorData>(
      `/memes/${memeId}`,
      this.withSignal(config),
    );
  }

  /**
   * voteMeme
   * Vote whether a meme is real or fake
   * @param memeId - Path parameter

   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `memesVoteMemeResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.memes.voteMeme(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public voteMeme(
    memeId: string | number,
    payload: memesVoteMemePayload,
    config?: AppRequestConfig,
  ): Promise<ApiResult<memesVoteMemeResponse, AppApiErrorData>> {
    return this.client.post<memesVoteMemeResponse, AppApiErrorData>(
      `/memes/${memeId}/vote`,
      payload,
      this.withSignal(config),
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  // --- CUSTOM CODE END ---
}
