// AUTO-GENERATED BY specshot (custom template — schema registry) - DO NOT DELETE MAGIC COMMENTS
// This template exports Zod schemas with the `Schema` naming convention
// and infers TypeScript types from them. Schemas are grouped in a registry object
// for convenient runtime access (e.g. `schemas.Pet.parse(input)`).

import { z } from "zod";

/**
 * Centralized schema registry.
 * Use for runtime validation: `schemas.Pet.parse(input)`
 */
export const schemas = {} as const;

// ─────────────────────────────────────────────
// Shared Error class
// ─────────────────────────────────────────────
export class ApiError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly body: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

// --- CUSTOM CODE START ---
// Add your custom schemas here. Do not remove these comments.
// --- CUSTOM CODE END ---
