// AUTO-GENERATED BY specshot (custom template — plain TS interfaces)
// This template separates type imports from schema imports using `import type`,
// and uses `interface` for query parameter types.

import { z } from "zod";

// ── Tag-specific schemas for pets ──
/** Pet runtime schema */
export const PetSchema = z.object({
  id: z.string(),
  name: z.string(),
  species: z.string(),
});

/** Pet inferred type */
export type Pet = z.infer<typeof PetSchema>;

/** CreatePetRequest runtime schema */
export const CreatePetRequestSchema = z.object({
  name: z.string(),
  species: z.string(),
});

/** CreatePetRequest inferred type */
export type CreatePetRequest = z.infer<typeof CreatePetRequestSchema>;

// ── Request & Response Types ──
/** Response type for listPets */
export type petsListPetsResponse = Pet[];

/** Request body for createPet */
export type petsCreatePetPayload = CreatePetRequest;

/** Response type for createPet */
export type petsCreatePetResponse = Pet;

/** Response type for getPet */
export type petsGetPetResponse = Pet;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
