// AUTO-GENERATED BY specshot (custom template — functional fetch API) - DO NOT DELETE MAGIC COMMENTS
// This template generates standalone async functions using native fetch().
// No BaseService, no ApiClient, no interceptors — just plain fetch wrappers.

import type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";
export type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";

import { ApiError } from "./models";

// ─────────────────────────────────────────────
// Base URL — configure via setBaseUrl()
// ─────────────────────────────────────────────
let _baseUrl = "";

/** Set the API base URL (e.g. "https://api.example.com"). */
export function setBaseUrl(url: string): void {
  _baseUrl = url.replace(/\/+$/, "");
}

/** Get the current base URL. */
export function getBaseUrl(): string {
  return _baseUrl;
}

/**
 * listPets
 * List all pets
 * @param init — Optional fetch init (headers, signal, etc.)
 * @returns `Promise<PetsListPetsResponse>`
 * @throws {ApiError} On non-2xx response
 */
export async function listPets(
  init?: RequestInit,
): Promise<PetsListPetsResponse> {
  let _url = `${_baseUrl}/pets`;
  const _res = await fetch(_url, {
    method: "get",
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `listPets failed: ${_res.status} ${_res.statusText}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<PetsListPetsResponse>;
}

/**
 * createPet
 * Create a pet

 * @param body — Request body
 * @param init — Optional fetch init (headers, signal, etc.)
 * @returns `Promise<PetsCreatePetResponse>`
 * @throws {ApiError} On non-2xx response
 */
export async function createPet(
  body: PetsCreatePetPayload,
  init?: RequestInit,
): Promise<PetsCreatePetResponse> {
  let _url = `${_baseUrl}/pets`;
  const _res = await fetch(_url, {
    method: "post",
    headers: { "Content-Type": "application/json", ...init?.headers },
    body: JSON.stringify(body),
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `createPet failed: ${_res.status} ${_res.statusText}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<PetsCreatePetResponse>;
}

/**
 * getPet
 * Get a pet by ID
 * @param petId — Path parameter
 * @param init — Optional fetch init (headers, signal, etc.)
 * @returns `Promise<PetsGetPetResponse>`
 * @throws {ApiError} On non-2xx response
 */
export async function getPet(
  petId: string | number,
  init?: RequestInit,
): Promise<PetsGetPetResponse> {
  let _url = `${_baseUrl}/pets/${petId}`;
  const _res = await fetch(_url, {
    method: "get",
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `getPet failed: ${_res.status} ${_res.statusText}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<PetsGetPetResponse>;
}

// --- CUSTOM CODE START ---
// Add your custom functions here. Do not remove these comments.
// --- CUSTOM CODE END ---
