// AUTO-GENERATED BY specshot (custom template — barrel exports, no Zod/plugins)
// Simply re-exports everything from services.

export * from "../services/pets.service";

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
