// AUTO-GENERATED BY specshot
import { z } from "zod";

import { Pet, PetSchema } from "./models";

// -- Specific Models for pets --
export const CreatePetRequestSchema = z.object({
  name: z.string(),
  age: z.number().optional(),
  tag: z.string().optional(),
});
export type CreatePetRequest = z.infer<typeof CreatePetRequestSchema>;

// -- Request & Response Types --

export type petsListPetsParams = {
  limit?: number;
};

export type petsListPetsResponse = Pet[];

export type petsCreatePetPayload = CreatePetRequest;

export type petsCreatePetResponse = Pet;

export type petsGetPetResponse = Pet;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
