// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  User,
  CreateUserRequest,
  LoginResult,
  userCreateUserPayload,
  userCreateUserResponse,
  userLoginUserParams,
  userLoginUserResponse,
  userGetUserResponse,
} from "./user.types";

export type {
  User,
  CreateUserRequest,
  LoginResult,
  userCreateUserPayload,
  userCreateUserResponse,
  userLoginUserParams,
  userLoginUserResponse,
  userGetUserResponse,
};

export class userService extends BaseService<"user"> {
  constructor(client: ApiClient) {
    super(client, "user");
  }

  /**
   * createUser
   * Create a user
   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `userCreateUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *   - `ok`: `true` on success, `false` on error
   */
  public createUser(
    payload: userCreateUserPayload,
    config?: AppRequestConfig,
  ): Promise<ApiResult<userCreateUserResponse, AppApiErrorData>> {
    return this.client.post<userCreateUserResponse, AppApiErrorData>(
      `/user`,
      payload,
      this.withSignal(config),
    );
  }

  /**
   * loginUser
   * Login a user
   * @param params - Query parameters (username, password)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `userLoginUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *   - `ok`: `true` on success, `false` on error
   */
  public loginUser(
    params: userLoginUserParams,
    config?: AppRequestConfig,
  ): Promise<ApiResult<userLoginUserResponse, AppApiErrorData>> {
    return this.client.get<userLoginUserResponse, AppApiErrorData>(
      `/user/login`,
      this.withSignal({ ...config, params } as AppRequestConfig),
    );
  }

  /**
   * getUser
   * Get user by username
   * @param username - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `userGetUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *   - `ok`: `true` on success, `false` on error
   */
  public getUser(
    username: string | number,
    config?: AppRequestConfig,
  ): Promise<ApiResult<userGetUserResponse, AppApiErrorData>> {
    return this.client.get<userGetUserResponse, AppApiErrorData>(
      `/user/${username}`,
      this.withSignal(config),
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  // --- CUSTOM CODE END ---
}
