// AUTO-GENERATED BY specshot (custom template — naming helpers demo)
// Demonstrates all available Handlebars naming helpers.
//
// Available helpers:
//           → Pets
//    → listPets
//           → Pets
//            → pets
//            → pets
//          → pets
//          → PETS
//   ...
//

export class ApiError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly body: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
