// AUTO-GENERATED BY specshot (custom template — naming helpers demo)
// Demonstrates naming helpers for service methods.
//
//  →
//  →
//  →
//  →
//  →
//  →
//  →

import type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";
export type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";

import { ApiError } from "./models";

// Class name via helper: Service
// File would be: .service.ts
// Constant name: Service

let _baseUrl = "";

export function setBaseUrl(url: string): void {
  _baseUrl = url.replace(/\/+$/, "");
}

export function getBaseUrl(): string {
  return _baseUrl;
}

/**
 * listPets
 *   PascalCase: ListPets
 *   camelCase:  listPets
 *   kebabCase:  list-pets
 *   snakeCase:  list_pets
 * @returns Promise<PetsListPetsResponse>
 * @throws {ApiError} On non-2xx response
 */
export async function listPets(
  init?: RequestInit,
): Promise<PetsListPetsResponse> {
  let _url = `${_baseUrl}/pets`;
  const _res = await fetch(_url, {
    method: "get",
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `listPets failed: ${_res.status}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<PetsListPetsResponse>;
}

/**
 * createPet
 *   PascalCase: CreatePet
 *   camelCase:  createPet
 *   kebabCase:  create-pet
 *   snakeCase:  create_pet

 * @param body — Request body (PetsCreatePetPayload)
 * @returns Promise<PetsCreatePetResponse>
 * @throws {ApiError} On non-2xx response
 */
export async function createPet(
  body: PetsCreatePetPayload,
  init?: RequestInit,
): Promise<PetsCreatePetResponse> {
  let _url = `${_baseUrl}/pets`;
  const _res = await fetch(_url, {
    method: "post",
    headers: { "Content-Type": "application/json", ...init?.headers },
    body: JSON.stringify(body),
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `createPet failed: ${_res.status}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<PetsCreatePetResponse>;
}

/**
 * getPet
 *   PascalCase: GetPet
 *   camelCase:  getPet
 *   kebabCase:  get-pet
 *   snakeCase:  get_pet
 * @param petId — Path parameter
 * @returns Promise<PetsGetPetResponse>
 * @throws {ApiError} On non-2xx response
 */
export async function getPet(
  petId: string | number,
  init?: RequestInit,
): Promise<PetsGetPetResponse> {
  let _url = `${_baseUrl}/pets/${petId}`;
  const _res = await fetch(_url, {
    method: "get",
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(`getPet failed: ${_res.status}`, _res.status, _errBody);
  }
  return _res.json() as Promise<PetsGetPetResponse>;
}

// --- CUSTOM CODE START ---
// Add your custom functions here. Do not remove these comments.
// --- CUSTOM CODE END ---
