// AUTO-GENERATED BY specshot (custom template — naming helpers demo)
// Shows naming helpers in action for each operation.

// Pet — PascalCase, Pet — camelCase, pet — kebab, pet — snake
export type Pet = {
  id: string;
  name: string;
  species: string;
};

// CreatePetRequest — PascalCase, CreatePetRequest — camelCase, create-pet-request — kebab, create_pet_request — snake
export type CreatePetRequest = {
  name: string;
  species: string;
};

// Operation: listPets
//   pascalCase: ListPets
//   camelCase:  listPets
//   kebabCase:  list-pets
//   snakeCase:  list_pets
//   toUpperCase: LISTPETS
//   toLowerCase: listpets

export type PetsListPetsResponse = Pet[];

// Operation: createPet
//   pascalCase: CreatePet
//   camelCase:  createPet
//   kebabCase:  create-pet
//   snakeCase:  create_pet
//   toUpperCase: CREATEPET
//   toLowerCase: createpet
export type PetsCreatePetPayload = CreatePetRequest;

export type PetsCreatePetResponse = Pet;

// Operation: getPet
//   pascalCase: GetPet
//   camelCase:  getPet
//   kebabCase:  get-pet
//   snakeCase:  get_pet
//   toUpperCase: GETPET
//   toLowerCase: getpet

export type PetsGetPetResponse = Pet;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
