// AUTO-GENERATED BY specshot (custom template — barrel exports)
// This template simply re-exports everything from services.
// No createApi(), no browserClient, no plugin system.

export * from "./services/pets.service";

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
