// AUTO-GENERATED BY specshot - MSW Browser Setup
import { setupWorker } from "msw/browser";
import { handlers } from "./index";

export function startMocks(
  options: Parameters<ReturnType<typeof setupWorker>["start"]>[0] = {},
) {
  if (handlers.length === 0) {
    console.warn(
      "[specshot] No MSW handlers are enabled. Mocking is disabled.",
    );
    return Promise.resolve();
  }

  const worker = setupWorker(...handlers);

  // Default to bypass unhandled requests so they hit the real API or proxy
  const defaultOptions = { onUnhandledRequest: "bypass" as const };

  return worker.start({ ...defaultOptions, ...options });
}
