// AUTO-GENERATED BY specshot - MSW handlers barrel
import { memesHandlers } from "./memes.handlers";
import { leaderboardHandlers } from "./leaderboard.handlers";

export const handlers = [...memesHandlers, ...leaderboardHandlers];
