// AUTO-GENERATED BY specshot - MSW handlers for leaderboard
import { http, HttpResponse, type PathParams, delay } from "msw";
import type { leaderboardGetLeaderboardResponse } from "../services/leaderboard.types";

/**
 * Get top players by score
 */
export const getLeaderboardHandler = http.get<PathParams<"/leaderboard">>(
  "/leaderboard",
  async ({ params }) => {
    return HttpResponse.json([] as leaderboardGetLeaderboardResponse, {
      status: 200,
    });
  },
);

export const leaderboardHandlers = [getLeaderboardHandler];
