// AUTO-GENERATED BY specshot - MSW handlers for memes
import { http, HttpResponse, type PathParams, delay } from "msw";
import type { memesListMemesResponse } from "../../services/memes.types";

/**
 * List memes to vote on
 */
export const listMemesHandler = http.get<PathParams<"/memes">>(
  "/memes",
  async ({ params }) => {
    return HttpResponse.json([] as memesListMemesResponse, { status: 200 });
  },
);

export const memesHandlers = [listMemesHandler];
