// AUTO-GENERATED BY specshot - MSW handlers for memes
import { http, HttpResponse, type PathParams, delay } from "msw";
import type {
  memesListMemesResponse,
  memesCreateMemePayload,
  memesGetMemeResponse,
  memesVoteMemeResponse,
  memesVoteMemePayload,
} from "../services/memes.types";

/**
 * List memes to vote on
 */
export const listMemesHandler = http.get<PathParams<"/memes">>(
  "/memes",
  async ({ params }) => {
    return HttpResponse.json(
      [
        {
          id: "veniam",
          imageUrl:
            "https://loremflickr.com/894/3558/meme?lock=936278379372377",
          caption: "amissio",
          category: "news",
          isReal: true,
          totalVotes: 597,
          realVotes: 827,
          fakeVotes: 889,
        },
        {
          id: "necessitatibus",
          imageUrl:
            "https://loremflickr.com/3854/3006/meme?lock=7628276725663412",
          caption: "nemo",
          category: "news",
          isReal: true,
          totalVotes: 739,
          realVotes: 335,
          fakeVotes: 524,
        },
      ],
      { status: 200 },
    );
  },
);

/**
 * Submit a new meme for voting
 */
export const createMemeHandler = http.post<PathParams<"/memes">>(
  "/memes",
  async ({ params, request }) => {
    const body = (await request.json()) as memesCreateMemePayload;
    return HttpResponse.json(null, { status: 201 });
  },
);

/**
 * Get a single meme by ID
 */
export const getMemeHandler = http.get<PathParams<"/memes/:memeId">>(
  "/memes/:memeId",
  async ({ params }) => {
    return HttpResponse.json({} as memesGetMemeResponse, { status: 200 });
  },
);

/**
 * Vote whether a meme is real or fake
 */
export const voteMemeHandler = http.post<PathParams<"/memes/:memeId/vote">>(
  "/memes/:memeId/vote",
  async ({ params, request }) => {
    const body = (await request.json()) as memesVoteMemePayload;
    return HttpResponse.json({} as memesVoteMemeResponse, { status: 201 });
  },
);

export const memesHandlers = [
  listMemesHandler,
  createMemeHandler,
  getMemeHandler,
  voteMemeHandler,
];
