// AUTO-GENERATED BY specshot - MSW handlers for memes
import { http, HttpResponse, type PathParams, delay } from "msw";
import type { memesListMemesResponse } from "../../services/memes.types";

export function getmemesHandlers(baseUrl: string = "") {
  return [
    /**
     * List memes to vote on
     */
    http.get(`${baseUrl}/memes`, async ({ params }) => {
      return HttpResponse.json(
        [
          {
            id: "ultra",
            imageUrl:
              "https://loremflickr.com/2117/911/meme?lock=3590475628504407",
            caption: "caput",
            category: "news",
            isReal: false,
            totalVotes: 538,
            realVotes: 662,
            fakeVotes: 303,
          },
          {
            id: "cunctatio",
            imageUrl:
              "https://loremflickr.com/2410/3432/meme?lock=5253031300156950",
            caption: "temptatio",
            category: "news",
            isReal: true,
            totalVotes: 793,
            realVotes: 282,
            fakeVotes: 310,
          },
          {
            id: "sollers",
            imageUrl:
              "https://loremflickr.com/684/3931/meme?lock=2750975146025184",
            caption: "denego",
            category: "news",
            isReal: true,
            totalVotes: 981,
            realVotes: 790,
            fakeVotes: 373,
          },
        ],
        { status: 200 },
      );
    }),
  ];
}
