// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type { InventoryGetInventoryResponse } from "./inventory.types";
import { InventoryGetInventoryResponseSchema } from "./inventory.types";

export type { InventoryGetInventoryResponse };

export class InventoryService extends BaseService<"inventory"> {
  constructor(client: ApiClient) {
    super(client, "inventory");
  }

  /**
   * getInventory
   * Returns pet inventories by status
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `InventoryGetInventoryResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.inventory.getInventory(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getInventory(
    config?: AppRequestConfig,
  ): CancelablePromise<
    ApiResult<InventoryGetInventoryResponse, AppApiErrorData>
  > {
    return this.client.get<InventoryGetInventoryResponse, AppApiErrorData>(
      `/inventory`,
      {
        ...this.withSignal(config),
        zodSchema: InventoryGetInventoryResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
