// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Request & Response Types --

export const InventoryGetInventoryResponseSchema = z.record(z.any());
export type InventoryGetInventoryResponse = z.infer<
  typeof InventoryGetInventoryResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
