// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { z } from "zod";


// --- CUSTOM CODE START ---
// Add your custom Zod models here. Do not remove these comments.
// --- CUSTOM CODE END ---
