// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  Order,
  OrdersListOrdersParams,
  OrdersListOrdersResponse,
  OrdersPlaceOrderPayload,
  OrdersPlaceOrderResponse,
  OrdersGetOrderResponse,
  OrdersCancelOrderResponse,
} from "./orders.types";
import {
  OrdersListOrdersResponseSchema,
  OrdersPlaceOrderResponseSchema,
  OrdersGetOrderResponseSchema,
} from "./orders.types";

export type {
  Order,
  OrdersListOrdersParams,
  OrdersListOrdersResponse,
  OrdersPlaceOrderPayload,
  OrdersPlaceOrderResponse,
  OrdersGetOrderResponse,
  OrdersCancelOrderResponse,
};

export class OrdersService extends BaseService<"orders"> {
  constructor(client: ApiClient) {
    super(client, "orders");
  }

  /**
   * listOrders
   * List orders with filters
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `OrdersListOrdersResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.orders.listOrders(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listOrders(
    params?: OrdersListOrdersParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<ApiResult<OrdersListOrdersResponse, AppApiErrorData>> {
    return this.client.get<OrdersListOrdersResponse, AppApiErrorData>(
      `/orders`,
      {
        ...this.withSignal(config),
        params,
        zodSchema: OrdersListOrdersResponseSchema,
      },
    );
  }

  /**
   * placeOrder
   * Place a new order

   * @param payload - Request body (`OrdersPlaceOrderPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `OrdersPlaceOrderResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.orders.placeOrder(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public placeOrder(
    payload: OrdersPlaceOrderPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<OrdersPlaceOrderResponse, AppApiErrorData>> {
    return this.client.post<OrdersPlaceOrderResponse, AppApiErrorData>(
      `/orders`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: OrdersPlaceOrderResponseSchema,
      },
    );
  }

  /**
   * getOrder
   * Get order details
   * @param orderId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `OrdersGetOrderResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.orders.getOrder(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getOrder(
    orderId: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<OrdersGetOrderResponse, AppApiErrorData>> {
    return this.client.get<OrdersGetOrderResponse, AppApiErrorData>(
      `/orders/${orderId}`,
      {
        ...this.withSignal(config),
        zodSchema: OrdersGetOrderResponseSchema,
      },
    );
  }

  /**
   * cancelOrder
   * Cancel an order
   * @param orderId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: void (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.orders.cancelOrder(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public cancelOrder(
    orderId: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<void, AppApiErrorData>> {
    return this.client.delete<AppApiErrorData>(`/orders/${orderId}`, {
      ...this.withSignal(config),
    });
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
