// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "@/api/core/base-service";
import { ApiClient } from "@/api/core/api-client";
import { ApiResult, CancelablePromise } from "@/api/core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";
import {
  PetsListPetsResponseSchema,
  PetsCreatePetResponseSchema,
  PetsGetPetResponseSchema,
} from "./pets.types";

export type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
};

export class PetsService extends BaseService<"pets"> {
  constructor(client: ApiClient) {
    super(client, "pets");
  }

  /**
   * listPets
   * List all pets
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `PetsListPetsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.pets.listPets(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listPets(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<PetsListPetsResponse, AppApiErrorData>> {
    return this.client.get<PetsListPetsResponse, AppApiErrorData>(`/pets`, {
      ...this.withSignal(config),
      zodSchema: PetsListPetsResponseSchema,
    });
  }

  /**
   * createPet
   * Create a pet

   * @param payload - Request body (`PetsCreatePetPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `PetsCreatePetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.pets.createPet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createPet(
    payload: PetsCreatePetPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<PetsCreatePetResponse, AppApiErrorData>> {
    return this.client.post<PetsCreatePetResponse, AppApiErrorData>(
      `/pets`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: PetsCreatePetResponseSchema,
      },
    );
  }

  /**
   * getPet
   * Get a pet by ID
   * @param petId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `PetsGetPetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.pets.getPet(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getPet(
    petId: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<PetsGetPetResponse, AppApiErrorData>> {
    return this.client.get<PetsGetPetResponse, AppApiErrorData>(
      `/pets/${petId}`,
      {
        ...this.withSignal(config),
        zodSchema: PetsGetPetResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  // --- CUSTOM CODE END ---
}
