// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for stores --
export const StoreSchema = z.object({
  id: z.string(),
  name: z.string(),
  address: z.string(),
  isActive: z.boolean().optional(),
});
export type Store = z.infer<typeof StoreSchema>;

// -- Request & Response Types --

export const StoresListStoresResponseSchema = z.array(StoreSchema);
export type StoresListStoresResponse = z.infer<
  typeof StoresListStoresResponseSchema
>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
