// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  User,
  UsersListUsersResponse,
  UsersCreateUserPayload,
  UsersCreateUserResponse,
  UsersLoginUserParams,
  UsersLoginUserResponse,
  UsersLogoutUserResponse,
} from "./users.types";
import {
  UsersListUsersResponseSchema,
  UsersCreateUserResponseSchema,
  UsersLoginUserResponseSchema,
  UsersLogoutUserResponseSchema,
} from "./users.types";

export type {
  User,
  UsersListUsersResponse,
  UsersCreateUserPayload,
  UsersCreateUserResponse,
  UsersLoginUserParams,
  UsersLoginUserResponse,
  UsersLogoutUserResponse,
};

export class UsersService extends BaseService<"users"> {
  constructor(client: ApiClient) {
    super(client, "users");
  }

  /**
   * listUsers
   * List users
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `UsersListUsersResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.users.listUsers(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listUsers(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<UsersListUsersResponse, AppApiErrorData>> {
    return this.client.get<UsersListUsersResponse, AppApiErrorData>(`/users`, {
      ...this.withSignal(config),
      zodSchema: UsersListUsersResponseSchema,
    });
  }

  /**
   * createUser
   * Create user

   * @param payload - Request body (`UsersCreateUserPayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `UsersCreateUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.users.createUser(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createUser(
    payload: UsersCreateUserPayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<UsersCreateUserResponse, AppApiErrorData>> {
    return this.client.post<UsersCreateUserResponse, AppApiErrorData>(
      `/users`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: UsersCreateUserResponseSchema,
      },
    );
  }

  /**
   * loginUser
   * Logs user into the system
   * @param params - Query parameters
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `UsersLoginUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.users.loginUser(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public loginUser(
    params?: UsersLoginUserParams,
    config?: Omit<AppRequestConfig, "params">,
  ): CancelablePromise<ApiResult<UsersLoginUserResponse, AppApiErrorData>> {
    return this.client.get<UsersLoginUserResponse, AppApiErrorData>(
      `/users/login`,
      {
        ...this.withSignal(config),
        params,
        zodSchema: UsersLoginUserResponseSchema,
      },
    );
  }

  /**
   * logoutUser
   * Logs out current logged in user session
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `UsersLogoutUserResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.users.logoutUser(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public logoutUser(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<UsersLogoutUserResponse, AppApiErrorData>> {
    return this.client.get<UsersLogoutUserResponse, AppApiErrorData>(
      `/users/logout`,
      {
        ...this.withSignal(config),
        zodSchema: UsersLogoutUserResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
