// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  CreatePetRequest,
  PetsListPetsParams,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";

export type {
  CreatePetRequest,
  PetsListPetsParams,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
};

export class PetsService extends BaseService<"pets"> {
  constructor(client: ApiClient) {
    super(client, "pets");
  }

  /**
   * listPets
   * List all pets
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `PetsListPetsResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.pets.listPets(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listPets(
    config?: Omit<AppRequestConfig, "params"> & { params?: PetsListPetsParams },
  ): Promise<ApiResult<PetsListPetsResponse, AppApiErrorData>> {
    return this.client.get<PetsListPetsResponse, AppApiErrorData>(
      `/pets`,
      this.withSignal(config),
    );
  }

  /**
   * createPet
   * Create a pet

   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `PetsCreatePetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.pets.createPet(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createPet(
    payload: PetsCreatePetPayload,
    config?: AppRequestConfig,
  ): Promise<ApiResult<PetsCreatePetResponse, AppApiErrorData>> {
    return this.client.post<PetsCreatePetResponse, AppApiErrorData>(
      `/pets`,
      payload,
      this.withSignal(config),
    );
  }

  /**
   * getPet
   * Get a pet by ID
   * @param petId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `PetsGetPetResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.pets.getPet(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getPet(
    petId: string | number,
    config?: AppRequestConfig,
  ): Promise<ApiResult<PetsGetPetResponse, AppApiErrorData>> {
    return this.client.get<PetsGetPetResponse, AppApiErrorData>(
      `/pets/${petId}`,
      this.withSignal(config),
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.

  // --- CUSTOM CODE END ---
}
