// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  Store,
  Order,
  CreateOrderRequest,
  StoreListStoresResponse,
  StorePlaceOrderPayload,
  StorePlaceOrderResponse,
  StoreGetOrderResponse,
} from "./store.types";

export type {
  Store,
  Order,
  CreateOrderRequest,
  StoreListStoresResponse,
  StorePlaceOrderPayload,
  StorePlaceOrderResponse,
  StoreGetOrderResponse,
};

export class StoreService extends BaseService<"store"> {
  constructor(client: ApiClient) {
    super(client, "store");
  }

  /**
   * listStores
   * List all stores
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoreListStoresResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.store.listStores(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listStores(
    config?: AppRequestConfig,
  ): Promise<ApiResult<StoreListStoresResponse, AppApiErrorData>> {
    return this.client.get<StoreListStoresResponse, AppApiErrorData>(
      `/stores`,
      this.withSignal(config),
    );
  }

  /**
   * placeOrder
   * Place an order for a pet

   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StorePlaceOrderResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.store.placeOrder(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public placeOrder(
    payload: StorePlaceOrderPayload,
    config?: AppRequestConfig,
  ): Promise<ApiResult<StorePlaceOrderResponse, AppApiErrorData>> {
    return this.client.post<StorePlaceOrderResponse, AppApiErrorData>(
      `/store/order`,
      payload,
      this.withSignal(config),
    );
  }

  /**
   * getOrder
   * Find purchase order by ID
   * @param orderId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoreGetOrderResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.store.getOrder(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getOrder(
    orderId: string | number,
    config?: AppRequestConfig,
  ): Promise<ApiResult<StoreGetOrderResponse, AppApiErrorData>> {
    return this.client.get<StoreGetOrderResponse, AppApiErrorData>(
      `/store/order/${orderId}`,
      this.withSignal(config),
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  // --- CUSTOM CODE END ---
}
