// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for user --
export const UserSchema = z.object({
  id: z.string(),
  username: z.string(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string().optional(),
});
export type User = z.infer<typeof UserSchema>;

export const CreateUserRequestSchema = z.object({
  username: z.string(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  email: z.string(),
});
export type CreateUserRequest = z.infer<typeof CreateUserRequestSchema>;

export const LoginResultSchema = z.object({
  token: z.string(),
  expiresIn: z.number().optional(),
});
export type LoginResult = z.infer<typeof LoginResultSchema>;

// -- Request & Response Types --
export type UserCreateUserPayload = CreateUserRequest;

export type UserCreateUserResponse = User;

export type UserLoginUserParams = {
  username: string;
  password: string;
};

export type UserLoginUserResponse = LoginResult;

export type UserGetUserResponse = User;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
