// AUTO-GENERATED BY specshot
import { z } from "zod";

// -- Specific Models for pets --
export const PetSchema = z.object({
  id: z.string(),
  name: z.string(),
  species: z.string(),
});
export type Pet = z.infer<typeof PetSchema>;

export const CreatePetRequestSchema = z.object({
  name: z.string(),
  species: z.string(),
});
export type CreatePetRequest = z.infer<typeof CreatePetRequestSchema>;

// -- Request & Response Types --

export const PetsListPetsResponseSchema = z.array(PetSchema);
export type PetsListPetsResponse = z.infer<typeof PetsListPetsResponseSchema>;

export type PetsCreatePetPayload = CreatePetRequest;

export const PetsCreatePetResponseSchema = PetSchema;
export type PetsCreatePetResponse = z.infer<typeof PetsCreatePetResponseSchema>;

export const PetsGetPetResponseSchema = PetSchema;
export type PetsGetPetResponse = z.infer<typeof PetsGetPetResponseSchema>;

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
