// AUTO-GENERATED BY specshot
import { z } from "zod";


// -- Specific Models for pets --
export const PetSchema = z.object({
  id: z.string(),
  name: z.string(),
  species: z.string(),
});
export type Pet = z.infer<typeof PetSchema>;

export const CreatePetRequestSchema = z.object({
  name: z.string(),
  species: z.string(),
});
export type CreatePetRequest = z.infer<typeof CreatePetRequestSchema>;


// -- Request & Response Types --


export type PetsListPetsResponse = Pet[];

export type PetsCreatePetPayload = CreatePetRequest;


export type PetsCreatePetResponse = Pet;



export type PetsGetPetResponse = Pet;


// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
