// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult, CancelablePromise } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type {
  Store,
  CreateStoreRequest,
  StoresListStoresResponse,
  StoresCreateStorePayload,
  StoresCreateStoreResponse,
  StoresGetStoreResponse,
} from "./stores.types";
import {
  StoresListStoresResponseSchema,
  StoresCreateStoreResponseSchema,
  StoresGetStoreResponseSchema,
} from "./stores.types";

export type {
  Store,
  CreateStoreRequest,
  StoresListStoresResponse,
  StoresCreateStorePayload,
  StoresCreateStoreResponse,
  StoresGetStoreResponse,
};

export class StoresService extends BaseService<"stores"> {
  constructor(client: ApiClient) {
    super(client, "stores");
  }

  /**
   * listStores
   * List all stores
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoresListStoresResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.stores.listStores(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listStores(
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<StoresListStoresResponse, AppApiErrorData>> {
    return this.client.get<StoresListStoresResponse, AppApiErrorData>(
      `/stores`,
      {
        ...this.withSignal(config),
        zodSchema: StoresListStoresResponseSchema,
      },
    );
  }

  /**
   * createStore
   * Create a store

   * @param payload - Request body (`StoresCreateStorePayload`)
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoresCreateStoreResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.stores.createStore(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createStore(
    payload: StoresCreateStorePayload,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<StoresCreateStoreResponse, AppApiErrorData>> {
    return this.client.post<StoresCreateStoreResponse, AppApiErrorData>(
      `/stores`,
      payload,
      {
        ...this.withSignal(config),
        zodSchema: StoresCreateStoreResponseSchema,
      },
    );
  }

  /**
   * getStore
   * Get a store by ID
   * @param storeId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoresGetStoreResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const req = api.stores.getStore(...);
   * // You can cancel the request if needed
   * // req.cancel();
   * const { data, error, ok } = await req;
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getStore(
    storeId: string | number,
    config?: AppRequestConfig,
  ): CancelablePromise<ApiResult<StoresGetStoreResponse, AppApiErrorData>> {
    return this.client.get<StoresGetStoreResponse, AppApiErrorData>(
      `/stores/${storeId}`,
      {
        ...this.withSignal(config),
        zodSchema: StoresGetStoreResponseSchema,
      },
    );
  }

  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  // --- CUSTOM CODE END ---
}
