// AUTO-GENERATED BY specshot - DO NOT DELETE MAGIC COMMENTS
import { BaseService } from "../../core/base-service";
import { ApiClient } from "../../core/api-client";
import { ApiResult } from "../../core/types";
import { AppRequestConfig, AppApiErrorData } from "../types";

import type { Store, CreateStoreRequest, StoresListStoresResponse, StoresCreateStorePayload, StoresCreateStoreResponse, StoresGetStoreResponse } from "./stores.types";

export type { Store, CreateStoreRequest, StoresListStoresResponse, StoresCreateStorePayload, StoresCreateStoreResponse, StoresGetStoreResponse };

export class StoresService extends BaseService<"stores"> {
  constructor(client: ApiClient) {
    super(client, "stores");
  }

  /**
   * listStores
   * List all stores
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoresListStoresResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.stores.listStores(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public listStores(
    config?: AppRequestConfig
  ): Promise<ApiResult<StoresListStoresResponse, AppApiErrorData>> {
    return this.client.get<StoresListStoresResponse, AppApiErrorData>(
      `/stores`,
      this.withSignal(config)
    );
  }

  /**
   * createStore
   * Create a store

   * @param payload - Request body
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoresCreateStoreResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.stores.createStore(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public createStore(
    payload: StoresCreateStorePayload,
    config?: AppRequestConfig
  ): Promise<ApiResult<StoresCreateStoreResponse, AppApiErrorData>> {
    return this.client.post<StoresCreateStoreResponse, AppApiErrorData>(
      `/stores`,
      payload,
      this.withSignal(config)
    );
  }

  /**
   * getStore
   * Get a store by ID
   * @param storeId - Path parameter
   * @param config - Request configuration (headers, timeout, signal, etc.)
   * @returns `{ data, error, ok }`
   *   - `data`: `StoresGetStoreResponse` (null on error)
   *   - `error`: `ApiError<AppApiErrorData>` | `ClientError` (null on success)
   *     Both have `.message`. Use `error.status` to check for HTTP errors,
   *     or `error.kind` for network/timeout/abort/parse errors.
   *   - `ok`: `true` on success, `false` on error
   *
   * @example
   * const { data, error, ok } = await api.stores.getStore(...);
   * if (!ok) {
   *   console.error(error.message);
   *   return;
   * }
   * // use `data` safely here
   */
  public getStore(
    storeId: string | number,
    config?: AppRequestConfig
  ): Promise<ApiResult<StoresGetStoreResponse, AppApiErrorData>> {
    return this.client.get<StoresGetStoreResponse, AppApiErrorData>(
      `/stores/${storeId}`,
      this.withSignal(config)
    );
  }


  // --- CUSTOM CODE START ---
  // Add your custom methods here. Do not remove these comments.
  
  // --- CUSTOM CODE END ---
}
