// AUTO-GENERATED BY specshot
import { ApiClient } from "../core/api-client";
export * from "./types";
export * from "./client";
export * from "./hooks";
import { createApiHooks } from "./hooks";
export * from "./plugins";

export * from "./services/businessunit.service";
import { BusinessUnitService } from "./services/businessunit.service";
export * from "./services/customer.service";
import { CustomerService } from "./services/customer.service";
export * from "./services/fulfillment.service";
import { FulfillmentService } from "./services/fulfillment.service";
export * from "./services/item.service";
import { ItemService } from "./services/item.service";
export * from "./services/saleorderschedule.service";
import { SaleorderscheduleService } from "./services/saleorderschedule.service";
export * from "./services/saleorder.service";
import { SaleOrderService } from "./services/saleorder.service";
export * from "./services/test.service";
import { TestService } from "./services/test.service";
export * from "./services/health.service";
import { HealthService } from "./services/health.service";

// ==========================================
// API Factory (For SSR and Client)
// ==========================================
export function createApi(client: ApiClient) {
  const instances = new Map<string, any>();
  return {
    client,
    get businessunit(): BusinessUnitService {
      let instance = instances.get("businessunit");
      if (!instance) {
        instance = new BusinessUnitService(client);
        instances.set("businessunit", instance);
      }
      return instance;
    },
    get customer(): CustomerService {
      let instance = instances.get("customer");
      if (!instance) {
        instance = new CustomerService(client);
        instances.set("customer", instance);
      }
      return instance;
    },
    get fulfillment(): FulfillmentService {
      let instance = instances.get("fulfillment");
      if (!instance) {
        instance = new FulfillmentService(client);
        instances.set("fulfillment", instance);
      }
      return instance;
    },
    get item(): ItemService {
      let instance = instances.get("item");
      if (!instance) {
        instance = new ItemService(client);
        instances.set("item", instance);
      }
      return instance;
    },
    get saleorderschedule(): SaleorderscheduleService {
      let instance = instances.get("saleorderschedule");
      if (!instance) {
        instance = new SaleorderscheduleService(client);
        instances.set("saleorderschedule", instance);
      }
      return instance;
    },
    get saleorder(): SaleOrderService {
      let instance = instances.get("saleorder");
      if (!instance) {
        instance = new SaleOrderService(client);
        instances.set("saleorder", instance);
      }
      return instance;
    },
    get test(): TestService {
      let instance = instances.get("test");
      if (!instance) {
        instance = new TestService(client);
        instances.set("test", instance);
      }
      return instance;
    },
    get health(): HealthService {
      let instance = instances.get("health");
      if (!instance) {
        instance = new HealthService(client);
        instances.set("health", instance);
      }
      return instance;
    },
  } as const;
}

export type ApiInstance = ReturnType<typeof createApi>;

// ==========================================
// Default Client API (Client-side usage only)
// ==========================================
// For SSR, DO NOT use this exported singleton. Instead, create a new client
// per request using `createApiClient()` and `createApi()` to prevent data leaks.
import { createApiClient } from "./client";
import { useAllPlugins } from "./plugins";

export const defaultClient = createApiClient();
useAllPlugins(defaultClient);

export const clientApi = createApi(defaultClient);

export const useApi = createApiHooks(clientApi);

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
