// AUTO-GENERATED BY specshot
import { ApiClient } from "../core/api-client";
export * from "./types";
export * from "./client";
export * from "./hooks";
import { createApiHooks } from "./hooks";
export * from "./plugins";

export * from "./services/businessunit.service";
import { BusinessUnitService } from "./services/businessunit.service";
export * from "./services/customer.service";
import { CustomerService } from "./services/customer.service";
export * from "./services/dispatch.service";
import { DispatchService } from "./services/dispatch.service";
export * from "./services/item.service";
import { ItemService } from "./services/item.service";
export * from "./services/parcel.service";
import { ParcelService } from "./services/parcel.service";
export * from "./services/saleorder.service";
import { SaleOrderService } from "./services/saleorder.service";
export * from "./services/test.service";
import { TestService } from "./services/test.service";
export * from "./services/fleet.service";
import { FleetService } from "./services/fleet.service";
export * from "./services/health.service";
import { HealthService } from "./services/health.service";

// ==========================================
// API Factory (For SSR and Client)
// ==========================================
export function createApi(client: ApiClient) {
  const instances = new Map<string, any>();
  return {
    client,
    get businessunit(): BusinessUnitService {
      let instance = instances.get("businessunit");
      if (!instance) {
        instance = new BusinessUnitService(client);
        instances.set("businessunit", instance);
      }
      return instance;
    },
    get customer(): CustomerService {
      let instance = instances.get("customer");
      if (!instance) {
        instance = new CustomerService(client);
        instances.set("customer", instance);
      }
      return instance;
    },
    get dispatch(): DispatchService {
      let instance = instances.get("dispatch");
      if (!instance) {
        instance = new DispatchService(client);
        instances.set("dispatch", instance);
      }
      return instance;
    },
    get item(): ItemService {
      let instance = instances.get("item");
      if (!instance) {
        instance = new ItemService(client);
        instances.set("item", instance);
      }
      return instance;
    },
    get parcel(): ParcelService {
      let instance = instances.get("parcel");
      if (!instance) {
        instance = new ParcelService(client);
        instances.set("parcel", instance);
      }
      return instance;
    },
    get saleorder(): SaleOrderService {
      let instance = instances.get("saleorder");
      if (!instance) {
        instance = new SaleOrderService(client);
        instances.set("saleorder", instance);
      }
      return instance;
    },
    get test(): TestService {
      let instance = instances.get("test");
      if (!instance) {
        instance = new TestService(client);
        instances.set("test", instance);
      }
      return instance;
    },
    get fleet(): FleetService {
      let instance = instances.get("fleet");
      if (!instance) {
        instance = new FleetService(client);
        instances.set("fleet", instance);
      }
      return instance;
    },
    get health(): HealthService {
      let instance = instances.get("health");
      if (!instance) {
        instance = new HealthService(client);
        instances.set("health", instance);
      }
      return instance;
    },
  } as const;
}

export type ApiInstance = ReturnType<typeof createApi>;

// ==========================================
// Default Client API (Client-side usage only)
// ==========================================
// For SSR, DO NOT use this exported singleton. Instead, create a new client
// per request using `createApiClient()` and `createApi()` to prevent data leaks.
import { createApiClient } from "./client";
import { useAllPlugins } from "./plugins";

export const defaultClient = createApiClient();
useAllPlugins(defaultClient);

export const clientApi = createApi(defaultClient);

export const useApi = createApiHooks(clientApi);

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
