// AUTO-GENERATED BY specshot - MSW handlers for pets
import { http, HttpResponse, type PathParams, delay } from "msw";
import type {
  PetsListPetsResponse,
  PetsCreatePetResponse,
  PetsCreatePetPayload,
  PetsGetPetResponse,
} from "../../services/pets.types";

export function getPetsHandlers(baseUrl: string = "") {
  return [
    /**
     * List all pets
     */
    http.get(`${baseUrl}/pets`, async ({ params }) => {
      return HttpResponse.json([] as PetsListPetsResponse, { status: 200 });
    }),
    /**
     * Create a pet
     */
    http.post(`${baseUrl}/pets`, async ({ params, request }) => {
      const body = (await request.json()) as PetsCreatePetPayload;
      return HttpResponse.json({} as PetsCreatePetResponse, { status: 201 });
    }),
    /**
     * Get a pet by ID
     */
    http.get(`${baseUrl}/pets/:petId`, async ({ params }) => {
      return HttpResponse.json({} as PetsGetPetResponse, { status: 200 });
    }),
  ];
}
