// AUTO-GENERATED BY specshot (custom template — plain TS types + ApiError) - DO NOT DELETE MAGIC COMMENTS

// ─────────────────────────────────────────────
// Shared Error class
// ─────────────────────────────────────────────
export class ApiError extends Error {
  constructor(
    message: string,
    public readonly status: number,
    public readonly body: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
