// AUTO-GENERATED BY specshot (custom template — plain TS types, no Zod)


// -- Specific Types for pets --
export type Pet = {
  id: string;
  name: string;
  species: string;
};

export type CreatePetRequest = {
  name: string;
  species: string;
};


// -- Request & Response Types --


export type PetsListPetsResponse = Pet[];

export type PetsCreatePetPayload = CreatePetRequest;


export type PetsCreatePetResponse = Pet;



export type PetsGetPetResponse = Pet;


// --- CUSTOM CODE START ---
// Add your custom types here. Do not remove these comments.
// --- CUSTOM CODE END ---
