// AUTO-GENERATED BY specshot (custom template — Observer Pattern) - DO NOT DELETE MAGIC COMMENTS
// Design Pattern: Observer — subscribe to API lifecycle events (before/after/error).
// Use case: Logging, analytics, caching, real-time UI updates on data changes.

import type { Pet, CreatePetRequest, PetsListPetsResponse, PetsCreatePetPayload, PetsCreatePetResponse, PetsGetPetResponse } from "./pets.types";
export type { Pet, CreatePetRequest, PetsListPetsResponse, PetsCreatePetPayload, PetsCreatePetResponse, PetsGetPetResponse } from "./pets.types";

import { ApiError } from "./models";

// ─────────────────────────────────────────────
// Event Types
// ─────────────────────────────────────────────

export type PetsServiceEventType = "before" | "after" | "error";

export interface PetsServiceEvent<T = unknown> {
  type: PetsServiceEventType;
  method: string;
  url: string;
  status?: number;
  data?: T;
  error?: Error;
  timestamp: number;
  durationMs: number;
}

type Listener<T = unknown> = (event: PetsServiceEvent<T>) => void;

// ─────────────────────────────────────────────
// Observable Service
// ─────────────────────────────────────────────

export class PetsService {
  private _baseUrl: string = "";
  private _listeners: Set<Listener> = new Set();

  /** Set the API base URL. */
  setBaseUrl(url: string): void {
    this._baseUrl = url.replace(/\/+$/, "");
  }

  // ── Observer API ──

  /** Subscribe to all events. Returns an unsubscribe function. */
  on(listener: Listener): () => void {
    this._listeners.add(listener);
    return () => this._listeners.delete(listener);
  }

  /** Subscribe to a specific event type. */
  onType(type: PetsServiceEventType, listener: Listener): () => void {
    return this.on((e) => {
      if (e.type === type) listener(e);
    });
  }

  /** Subscribe to "before" events (e.g. for loading indicators). */
  onBefore(listener: Listener): () => void {
    return this.onType("before", listener);
  }

  /** Subscribe to "after" events (e.g. for cache invalidation). */
  onAfter(listener: Listener): () => void {
    return this.onType("after", listener);
  }

  /** Subscribe to "error" events (e.g. for error reporting). */
  onError(listener: Listener): () => void {
    return this.onType("error", listener);
  }

  private _emit(event: PetsServiceEvent): void {
    for (const listener of this._listeners) {
      try {
        listener(event);
      } catch (err) {
        // Listener errors should never break the request flow
        console.error("[PetsService] Listener error:", err);
      }
    }
  }

  private async _request<T>(
    method: string,
    url: string,
    body?: unknown,
  ): Promise<T> {
    const _start = performance.now();
    this._emit({
      type: "before",
      method,
      url,
      timestamp: Date.now(),
      durationMs: 0,
    });

    try {
      const _res = await fetch(url, {
        method,
        headers: body ? { "Content-Type": "application/json" } : {},
        ...(body ? { body: JSON.stringify(body) } : {}),
      });

      if (!_res.ok) {
        const _errBody = await _res.text().catch(() => "");
        const _error = new ApiError(`${method} ${url} failed: ${_res.status}`, _res.status, _errBody);
        this._emit({
          type: "error",
          method,
          url,
          status: _res.status,
          error: _error,
          timestamp: Date.now(),
          durationMs: performance.now() - _start,
        });
        throw _error;
      }

      const _data = await _res.json() as T;
      this._emit({
        type: "after",
        method,
        url,
        status: _res.status,
        data: _data,
        timestamp: Date.now(),
        durationMs: performance.now() - _start,
      });
      return _data;
    } catch (err) {
      if (err instanceof ApiError) throw err;
      const _error = err as Error;
      this._emit({
        type: "error",
        method,
        url,
        error: _error,
        timestamp: Date.now(),
        durationMs: performance.now() - _start,
      });
      throw _error;
    }
  }

  /**
   * listPets
   * List all pets
   * @throws {ApiError} On non-2xx response
   */
  async listPets(
  ): Promise<PetsListPetsResponse> {
    let _url = `${this._baseUrl}/pets`;
    return this._request<PetsListPetsResponse>("get", _url);
  }

  /**
   * createPet
   * Create a pet
   * @throws {ApiError} On non-2xx response
   */
  async createPet(
    body: PetsCreatePetPayload,
  ): Promise<PetsCreatePetResponse> {
    let _url = `${this._baseUrl}/pets`;
    return this._request<PetsCreatePetResponse>("post", _url, body);
  }

  /**
   * getPet
   * Get a pet by ID
   * @throws {ApiError} On non-2xx response
   */
  async getPet(
    petId: string | number,
  ): Promise<PetsGetPetResponse> {
    let _url = `${this._baseUrl}/pets/${petId}`;
    return this._request<PetsGetPetResponse>("get", _url);
  }

}

// Convenience: shared instance
export const petsService = new PetsService();

// --- CUSTOM CODE START ---
// Add your custom code here. Do not remove these comments.
// --- CUSTOM CODE END ---
