// AUTO-GENERATED BY specshot
import { ApiClient } from "../core/api-client";
export * from "./types";
export * from "./client";
export * from "./plugins";

export * from "./services/pets.service";
import { PetsService } from "./services/pets.service";
export * from "./services/stores.service";
import { StoresService } from "./services/stores.service";

export function createApi(client: ApiClient) {
  return {
    client,
    pets: new PetsService(client),
    stores: new StoresService(client),
  } as const;
}

// Client-side singletons for convenient browser usage (e.g. SWR)
import { createApiClient } from "./client";
import { useAllPlugins } from "./plugins";

export const browserClient = createApiClient();
useAllPlugins(browserClient);

export const browserApi = createApi(browserClient);

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
