// AUTO-GENERATED BY specshot (custom template — barrel exports)

export * from "./pets.service";

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
