// AUTO-GENERATED BY specshot (custom template — Builder Pattern) - DO NOT DELETE MAGIC COMMENTS
// Design Pattern: Builder — fluently build complex requests with chained configuration.
// Use case: Complex queries with many optional params, custom headers per request, retry strategies.

import type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";
export type {
  Pet,
  CreatePetRequest,
  PetsListPetsResponse,
  PetsCreatePetPayload,
  PetsCreatePetResponse,
  PetsGetPetResponse,
} from "./pets.types";

import { ApiError, RequestBuilder } from "./models";

// ─────────────────────────────────────────────
// Service — uses builders for each operation
// ─────────────────────────────────────────────

let _baseUrl = "";

export function setBaseUrl(url: string): void {
  _baseUrl = url.replace(/\/+$/, "");
}

export function getBaseUrl(): string {
  return _baseUrl;
}

/**
 * listPets
 * List all pets
 * @returns RequestBuilder for fluent configuration
 * @throws {ApiError} On non-2xx response (when executed)
 */
export function listPets(): RequestBuilder<PetsListPetsResponse> {
  let _url = `${_baseUrl}/pets`;
  const builder = new RequestBuilder<PetsListPetsResponse>("get", _url);

  return builder;
}

/**
 * createPet
 * Create a pet
 * @returns RequestBuilder for fluent configuration
 * @throws {ApiError} On non-2xx response (when executed)
 */
export function createPet(): RequestBuilder<PetsCreatePetResponse> {
  let _url = `${_baseUrl}/pets`;
  const builder = new RequestBuilder<PetsCreatePetResponse>("post", _url);

  // Call .body(data) on the builder to set the request body
  return builder;
}

/**
 * getPet
 * Get a pet by ID
 * @returns RequestBuilder for fluent configuration
 * @throws {ApiError} On non-2xx response (when executed)
 */
export function getPet(
  petId: string | number,
): RequestBuilder<PetsGetPetResponse> {
  let _url = `${_baseUrl}/pets/${petId}`;
  const builder = new RequestBuilder<PetsGetPetResponse>("get", _url);

  return builder;
}

// --- CUSTOM CODE START ---
// Add your custom code here. Do not remove these comments.
// --- CUSTOM CODE END ---
