// AUTO-GENERATED BY specshot
import { ApiClient } from "../core/api-client";
export * from "./types";
export * from "./client";
export * from "./interceptors";

export * from "./services/pets.service";
import { petsService } from "./services/pets.service";
export * from "./services/store.service";
import { storeService } from "./services/store.service";
export * from "./services/user.service";
import { userService } from "./services/user.service";

export function createApi(client: ApiClient) {
  return {
    client,
    pets: new petsService(client),
    store: new storeService(client),
    user: new userService(client),
  } as const;
}

// Client-side singletons for convenient browser usage (e.g. SWR)
import { createApiClient } from "./client";
import { useAllPlugins } from "./interceptors";

export const browserClient = createApiClient();
useAllPlugins(browserClient);

export const browserApi = createApi(browserClient);

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
