/**
 * AUTO-GENERATED BY specshot
 *
 * Shared utility types and helpers for API hooks (React Query & SWR).
 * Do not edit manually — regenerate with `npx specshot generate`.
 */
import { BaseService } from "../core/base-service";
import type { ApiError, ClientError, ApiResult } from "../core/types";
import type { AppApiErrorData } from "./types";

// ============================================================================
// Shared error type
// ============================================================================

export type ApiHookError<TErrorData = AppApiErrorData> =
  | ApiError<TErrorData>
  | ClientError
  | Error;

// ============================================================================
// Shared type helpers
// ============================================================================

type UnwrapApiResult<T> = T extends ApiResult<infer U, any> ? U : never;
export type MethodData<TMethod extends (...args: any[]) => Promise<any>> =
  UnwrapApiResult<Awaited<ReturnType<TMethod>>>;

// ============================================================================
// Cache-key helper
// ============================================================================

/**
 * Filter out RequestConfig-shaped objects from hook arguments so they are not
 * included in cache/query keys.
 */
export function extractCacheKeyArgs(args: any[]): any[] {
  return args.filter(
    (arg) =>
      !(
        typeof arg === "object" &&
        arg !== null &&
        ("signal" in arg || "headers" in arg || "timeout" in arg)
      ),
  );
}

// ============================================================================
// Proxy type helpers (shared shape; concrete proxy methods live in each adapter)
// ============================================================================

export type ApiHooksProxy<TApi, TProxyService> = {
  [S in keyof TApi]: TApi[S] extends BaseService<any>
    ? TProxyService
    : never;
};
