// AUTO-GENERATED BY specshot
import { ApiClient } from "../core/api-client";
export * from "./types";
export * from "./client";
export * from "./hooks";
import { createApiHooks } from "./hooks";
export * from "./interceptors";

export * from "./services/memes.service";
import { MemesService } from "./services/memes.service";
export * from "./services/leaderboard.service";
import { LeaderboardService } from "./services/leaderboard.service";

export function createApi(client: ApiClient) {
  return {
    client,
    memes: new MemesService(client),
    leaderboard: new LeaderboardService(client),
  } as const;
}

// Client-side singletons for convenient browser usage (e.g. SWR)
import { createApiClient } from "./client";
import { useAllPlugins } from "./interceptors";

export const browserClient = createApiClient();
useAllPlugins(browserClient);

export const browserApi = createApi(browserClient);

export const useApi = createApiHooks(browserApi);

// --- CUSTOM CODE START ---
// Add your custom exports here. Do not remove these comments.
// --- CUSTOM CODE END ---
