// AUTO-GENERATED BY specshot (custom template — functional fetch API, no Zod) - DO NOT DELETE MAGIC COMMENTS
// Standalone async functions using native fetch(). No BaseService, no ApiClient.

import type {
  Pet,
  CreatePetRequest,
  petsListPetsResponse,
  petsCreatePetPayload,
  petsCreatePetResponse,
  petsGetPetResponse,
} from "../types/pets.types";
export type {
  Pet,
  CreatePetRequest,
  petsListPetsResponse,
  petsCreatePetPayload,
  petsCreatePetResponse,
  petsGetPetResponse,
} from "../types/pets.types";

import { ApiError } from "../models/models";

// ─────────────────────────────────────────────
// Base URL — configure via setBaseUrl()
// ─────────────────────────────────────────────
let _baseUrl = "";

/** Set the API base URL (e.g. "https://api.example.com"). */
export function setBaseUrl(url: string): void {
  _baseUrl = url.replace(/\/+$/, "");
}

/** Get the current base URL. */
export function getBaseUrl(): string {
  return _baseUrl;
}

/**
 * listPets
 * List all pets
 * @param init — Optional fetch init (headers, signal, etc.)
 * @returns `Promise<petsListPetsResponse>`
 * @throws {ApiError} On non-2xx response
 */
export async function listPets(
  init?: RequestInit,
): Promise<petsListPetsResponse> {
  let _url = `${_baseUrl}/pets`;
  const _res = await fetch(_url, {
    method: "get",
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `listPets failed: ${_res.status} ${_res.statusText}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<petsListPetsResponse>;
}

/**
 * createPet
 * Create a pet

 * @param body — Request body
 * @param init — Optional fetch init (headers, signal, etc.)
 * @returns `Promise<petsCreatePetResponse>`
 * @throws {ApiError} On non-2xx response
 */
export async function createPet(
  body: petsCreatePetPayload,
  init?: RequestInit,
): Promise<petsCreatePetResponse> {
  let _url = `${_baseUrl}/pets`;
  const _res = await fetch(_url, {
    method: "post",
    headers: { "Content-Type": "application/json", ...init?.headers },
    body: JSON.stringify(body),
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `createPet failed: ${_res.status} ${_res.statusText}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<petsCreatePetResponse>;
}

/**
 * getPet
 * Get a pet by ID
 * @param petId — Path parameter
 * @param init — Optional fetch init (headers, signal, etc.)
 * @returns `Promise<petsGetPetResponse>`
 * @throws {ApiError} On non-2xx response
 */
export async function getPet(
  petId: string | number,
  init?: RequestInit,
): Promise<petsGetPetResponse> {
  let _url = `${_baseUrl}/pets/${petId}`;
  const _res = await fetch(_url, {
    method: "get",
    ...init,
  });
  if (!_res.ok) {
    const _errBody = await _res.text().catch(() => "");
    throw new ApiError(
      `getPet failed: ${_res.status} ${_res.statusText}`,
      _res.status,
      _errBody,
    );
  }
  return _res.json() as Promise<petsGetPetResponse>;
}

// --- CUSTOM CODE START ---
// Add your custom functions here. Do not remove these comments.
// --- CUSTOM CODE END ---
